### PR TITLE
fix(useDeviceList): audioInputs doesn't update if camera permission is `granted`

### LINKED ISSUE #4558: audioInputs doesn't update if camera permission is 'granted'
If at some point camera's permission in browser is 'granted' and microphone's permission is requested, after granting permission to microphone audioInputs and audioOutputs lists are not updated.

Is there any chance to fix this in 11.x ?

PR [link](https://github.com/vueuse/vueuse/pull/4559)

### PR DESCRIPTION
**Pull request by Nikitatopodin**
fixes #4558 

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

Fix bug when camera permission in browser is already granted and after you grant permission to microphone lists of audio(Input/Output) devices don't update.

### CODE REVIEW

File: packages/core/useDevicesList/index.ts [hunk 1]
```diff
@@ -73,13 +73,15 @@ export function useDevicesList(options: UseDevicesListOptions = {}): UseDevicesL
   }
 
   async function ensurePermissions() {
+    const deviceName = constraints.video ? 'camera' : 'microphone'
```
Comment (OrbisK) [inline packages/core/useDevicesList/index.ts:76]: maybe we should compute the `deviceName`

**Review by ilyaliao — APPROVED** [review]

File: packages/core/useDevicesList/index.ts (hunk 1 above)
Comment (Nikitatopodin) [reply packages/core/useDevicesList/index.ts:76]: Do we really need this as a computed?
