### PR TITLE
fix(useVirtualList): resolve invalid watch source

### LINKED ISSUE #4854: BUG | `useVirtualList` | Invalid watch source with doc example
### Describe the bug

When using the "simple list" example in the `useVirtualList` docs:

```js
import { useVirtualList } from '@vueuse/core'

const { list, containerProps, wrapperProps } = useVirtualList(
  Array.from(Array.from({ length: 99999 }).keys()),
  {
    // Keep `itemHeight` in sync with the item's row.
    itemHeight: 22,
  },
)
```
console warnings appear about the provided data not being a valid watch source.

### Reproduction

https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wAjAAGSbEyak9bYLY7fYgI4nAhEHGIPHDGbWZ7sLhnDFfFA-GRyBS8ADCrAiiCgf3MrBMKBu2Fk+UKKkleDArGQMPkGWhshQCKRIBRgxGYwEQmms2GbI5XMQJPJlOpG0Q2z2hwAuswjHQDMa0KAAIJgMCTBboUCpLUGCCpIgAHio2RUxAopQ2AF4ADogGYqiBmRAcAAKHG8yALKmQoSD+bNiDo8D6aA6pNJYE2BYAfHnzCpU+nM9naU3khAI2XK9X+4OVEvh2niBmKLUOE3grRTOYgvXa2gYIgQtu45MPb2QHWG4gm7oW23pB3Go0ewuh8uVAAlViRDtgGAUwLyoRNXAOA5F2XZNhlXAch1g+DByQ7I+2eYVpCIOgtTqaQVGAvFFDoDhpFIQwSnrFQDhqKs8BUAByB0bk5OpEAYwdByLKjgIPaRGBUItpBLbBZyrQYBKnGcK3E5waJzfwbmI0jyIMSjpG0aDQw4CoQkmIw6O0bTdP0wzeJseBpF0DsAE47Ls6j7EmE8QmQbR7HsRhoOAaCl1GFQAGlEEQMAVAAAx3PAAAknz6MK9zrEJbCSYJdHiR8QNoBjnCrSJJl8zLotil8VDfLyhyOQd7EZSCgA

### System Info

```Shell
System:
    OS: Linux 6.6 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 7.47 GB / 9.71 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 22.17.0 - ~/.nvm/versions/node/v22.17.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 10.9.2 - ~/.nvm/versions/node/v22.17.0/bin/npm
    pnpm: 10.7.0 - ~/.local/share/pnpm/pnpm
  npmPackages:
    @vueuse/core: ^13.5.0 => 13.5.0
    vue: ^3.5.17 => 3.5.17
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vueuse.org/guide).
- [x] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by rzzf**
### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

Ensure that the `list` being listened to is always reactive data.

### Additional context

fixes #4854

### CODE REVIEW

File: packages/core/useVirtualList/index.ts [hunk 1]
```diff
@@ -201,7 +202,7 @@ function createGetDistance<T>(itemSize: UseVirtualListItemSize, source: UseVirtu
 }
 
 function useWatchForSizes<T>(size: UseVirtualElementSizes, list: MaybeRef<readonly T[]>, containerRef: Ref<HTMLElement | null>, calculateRange: () => void) {
-  watch([size.width, size.height, list, containerRef], () => {
+  watch([size.width, size.height, toRef(list), containerRef], () => {
```
Comment (OrbisK) [inline packages/core/useVirtualList/index.ts]:
```suggestion
  watch([size.width, size.height, () => toValue(list), containerRef], () => {
```

Comment (OrbisK) [reply packages/core/useVirtualList/index.ts]: or `unref`, because we dont have `MaybeRefOrGetter`

**Comment by rzzf** [comment]
@OrbisK Thank you for your review, I have updated the code.

**Review by OrbisK — DISMISSED** [review]

**Review by ilyaliao — APPROVED** [review]

File: packages/core/useVirtualList/index.ts (hunk 1 above)
Comment (43081j) [reply packages/core/useVirtualList/index.ts]: is this any slower than using the original ref if it was one?

i.e. is it slower to watch a function than a ref?

what is the benefit of `() => toValue(list)` over `toRef(list)`? (not saying either is better, just wondering if there's a gain)

**Comment by 43081j** [comment]
can you add a test too?

just set the list as a fixed array or something instead of a ref, in the test

if you also catch up from main, the docs build will succeed (although happy to merge regardless of that in this case)

**Comment by rzzf** [comment]
> can you add a test too?
> 
> just set the list as a fixed array or something instead of a ref, in the test
> 
> if you also catch up from main, the docs build will succeed (although happy to merge regardless of that in this case)

Okey, Tonight I will increase the test cases.

File: packages/core/useVirtualList/index.ts (hunk 1 above)
Comment (OrbisK) [reply packages/core/useVirtualList/index.ts]: Maybe we should benachmark this.

**Comment by rzzf** [comment]
> can you add a test too?
> 
> just set the list as a fixed array or something instead of a ref, in the test
> 
> if you also catch up from main, the docs build will succeed (although happy to merge regardless of that in this case)

Thank you for your review, I have added test case.

File: packages/core/useVirtualList/index.ts (hunk 1 above)
Comment (rzzf) [reply packages/core/useVirtualList/index.ts]: I am sorry, I am not familiar with benchmark tests. Can I do anything else?

File: packages/core/useVirtualList/index.test.ts [hunk 2]
```diff
@@ -1,11 +1,21 @@
...
   it('should be defined', () => {
     expect(useVirtualList).toBeDefined()
   })
+
+  it('should not warn when list is a plain array', async () => {
+    const spy = vi.spyOn(console, 'warn').mockImplementation(() => {})
+
+    useVirtualList(['a', 'b', 'c', 'd', 'e', 'f'], { itemWidth: () => 50, overscan: 1 })
+
+    expect(spy).not.toHaveBeenCalled()
```
Comment (43081j) [inline packages/core/useVirtualList/index.test.ts]: i dont think this'll ever be called since we don't console.warn in there

either way, we should test that mutations are observed instead i think

something like this:

```ts
    const items = shallowRef(['a', 'b'])
    const {
      list,
      containerProps: { ref: containerRef },
      scrollTo,
    } = useVirtualList(items, { itemHeight: () => 50 })
    const div = { ...document.createElement('div'), clientHeight: 100 }

    containerRef.value = div
    scrollTo(0)

    items.value = ['c', 'd']
    await nextTick()

    expect(list.value.map(i => i.data)).toEqual(['c', 'd'])

```

the test is that non-ref lists are observed

Comment (rzzf) [reply packages/core/useVirtualList/index.test.ts]: Umm, But the issue we need to fix is that when passing a plain list to watch, it sends a warning, and console.warn is called within watch.

I restored the code and retained the test code, this test case will not pass.
image


Perhaps we should keep them both at the same time?

something like this?
```ts
it('should not warn when list is a plain array', async () => {
    const spy = vi.spyOn(console, 'warn').mockImplementation(() => {})
    const items = shallowRef(['a', 'b'])
    const {
      list,
      containerProps: { ref: containerRef },
      scrollTo,
    } = useVirtualList(items.value, { itemHeight: () => 50 })
    const div = { ...document.createElement('div'), clientHeight: 100 }

    containerRef.value = div
    scrollTo(0)

    items.value = ['c', 'd']
    await nextTick()

    expect(spy).not.toHaveBeenCalled()
    expect(list.value.map(i => i.data)).toEqual(['a', 'b'])
  })
```

Comment (43081j) [reply packages/core/useVirtualList/index.test.ts]: the warning is just a side effect of us doing something wrong internally, though

if we were writing this function from scratch, we would just test that you can use it with a ref and without a ref

we're getting a warning because there's a bug, not because this function is meant to warn

that warning could go away any day, unrelated to this function. so it wouldn't be a concrete assertion

Comment (rzzf) [reply packages/core/useVirtualList/index.test.ts]: Thank you very much for pointing that out. I agree with your perspective.

Comment (rzzf) [reply packages/core/useVirtualList/index.test.ts]: I'm not very experienced in writing tests, so please feel free to point out any issues. I really appreciate your patience and understanding.

File: packages/core/useVirtualList/index.test.ts [hunk 3]
```diff
@@ -6,6 +6,19 @@ describe('useVirtualList', () => {
   it('should be defined', () => {
     expect(useVirtualList).toBeDefined()
   })
+
+  it('should not warn when list is a plain array', () => {
```
Comment (43081j) [inline packages/core/useVirtualList/index.test.ts]: this should now be something like:

> should accept plain arrays as input

Comment (rzzf) [reply packages/core/useVirtualList/index.test.ts]: done, Thanks!

File: packages/core/useVirtualList/index.ts (hunk 1 above)
Comment (43081j) [reply packages/core/useVirtualList/index.ts]: Don't worry about it. This is fine as it is 👍

**Review by ilyaliao — APPROVED** [review]
