### PR TITLE
fix(useElementSize): use getBoundingClientRect get element size on SVG

### LINKED ISSUE #3939: useElementSize returns NaN for SVG text element
### Describe the bug

When I try to use useElementSize to layout a text element in SVG, I find that the `width.value/height.value` returned is always NaN.

Maybe fixed by #3940 

### Reproduction

https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wAjAAGSbEyak9bYLY7fYgI4nAhEHGIPHDGbWZ7sLhnDFfFA-GRyBS8ADCrAiiCgf3MrBMKBu2Fk+UKKkleDArGQMPkGWhshQCKRIBRgxGYwEQmms2GbI5XMQJPJlOpG0Q2z2hwAuswjHQDMa0KAAIJgMCTBboUCpLUGCCpQGKADiKk8tBs0hczmklSQ2YV-huAFEgwQVQC6AAvRBoAA62AAPFRsiprEYALz1ljEeAAdQqEcQHB7KmQoSD3ZAkToVGkujQNWCFBmKqzPYAfI2VCom8g++3EF2ewf4GPZ-PdNOyaSwJsx9ee7f72PiLDIgAhVibaeklT-reKi3luO67nuqSbNmHbTpB0gAErHmOIQ3rQoHmOBu5NtIyCQNgm6NKSjQACzDMSjRkU2ww4Xh24YVh1GetIdEMWedFUa2xCbs8wrSEQdBanU2bAMWiBlpmlY1mkBw1BwswqAA5A6NycnUiAKY2AnahwwlHkYjBJImdgqDJRhyXgikLApADcjaNmuE7xExiEmJ2enaPYtm2PIbBBpMXjwNocEufY9k+bpl4LgZuiIHQ8B9CZKhuXi4kVtIVa1kFznHp5jaREZujaBgkW6NFsXxdIfo6MQjidpuKgOVKiD+awgU1QZIkCQQraJnW8QcKoBy5QoByjUAA

### System Info

```Shell
VueUse playground
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by siaikin**
### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

* fix #3939 

### Additional context

Use `getBoundingClientRect` instead of `window.getComputedStyle`.

Because when `window.getComputedStyle` is used on SVG `<text>` elements, the width/height will return `auto`, which causes `Number.parseFloat` to return **NaN**.

### CODE REVIEW

File: packages/core/useElementSize/index.ts [hunk 1]
```diff
@@ -38,9 +38,9 @@ export function useElementSize(
       if (window && isSVG.value) {
         const $elem = unrefElement(target)
         if ($elem) {
-          const styles = window.getComputedStyle($elem)
-          width.value = Number.parseFloat(styles.width)
-          height.value = Number.parseFloat(styles.height)
+          const rect = $elem.getBoundingClientRect()
+          width.value = Number.parseFloat(rect.width)
```
Comment (x13771944402) [inline packages/core/useElementSize/index.ts:42]: The types of (rect. width and rect. height) are already numbers, so there is no need to convert them using number. parseFloat

**Review by antfu — APPROVED** [review]
