### PR TITLE
fix(useMediaQuery): the return value should be computed

### LINKED ISSUE #4272: useBreakpoints doesn't adhere its own return type
### Describe the bug

`UseBreakpointsReturn` claims that methods such as `greater` return a computed ref but in fact they return a plain ref from the `useMediaQuery` composable so the actual return of `useBreakpoints` composable is not what `UseBreakpointsReturn` type claims it to be.

In my opinion the types should be in sync and the refs should not be mutable. In my project i solved it by running the refs through `readonly`.

### Reproduction

Not necessary

### System Info

```Shell
Not necessary
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by alexzhang1030**
### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

fixes #4272

The return value of useMediaQuery should be a getter(readonly computed value), for the general scenario. This will fix #4272 automatically.

### CODE REVIEW

File: packages/core/useMediaQuery/index.ts [hunk 1]
```diff
@@ -58,5 +58,5 @@ export function useMediaQuery(query: MaybeRefOrGetter<string>, options: Configur
     mediaQuery = undefined
   })
 
-  return matches
+  return computed(() => matches.value)
```
Comment (43081j) [inline packages/core/useMediaQuery/index.ts:61]: could it make more sense to wrap it in a readonly instead?

```suggestion
return readonly(matches)
```

presumably a `computed` is so you can compute something, whereas `readonly` will just wrap an existing ref as-is

(i could be wrong, tell me if i am!)

Comment (alexzhang1030) [reply packages/core/useMediaQuery/index.ts:61]: according to the vue docs, 

>  Takes an object (reactive or plain) or a ref and returns a readonly proxy to the original.

`readonly` is more proper for a `reactive` object.

and `computed` is lazy...

Comment (antfu) [reply packages/core/useMediaQuery/index.ts:61]: Yeah, I think both should work in this case. In terms of memory usage, `readonly` is definitely a bit more efficient. But the benefit of `computed` is that it deduces the value and guards unchanged effects to be triggered.

File: packages/core/useColorMode/index.test.ts [hunk 2]
```diff
@@ -16,7 +17,7 @@ describe('useColorMode', () => {
   })
 
   beforeEach(() => {
-    usePreferredDark().value = false
+    (usePreferredDark() as Ref<boolean>).value = false
```
Comment (antfu) [inline packages/core/useColorMode/index.test.ts:20]: I am not sure why we tested like this before. But isn't that the change to `computed` make this statement invalid?

Comment (alexzhang1030) [reply packages/core/useColorMode/index.test.ts:20]: This is for type-checking.

The value is mocked as a ref. https://github.com/vueuse/vueuse/pull/4403/files#diff-7811d4dbacf020831d35d217e1b1d3036a472d6a79ede4e1172d06cf9b58937dR12-R16

Comment (alexzhang1030) [reply packages/core/useColorMode/index.test.ts:20]: image

Comment (alexzhang1030) [reply packages/core/useColorMode/index.test.ts:20]: I’m not an expert in mocking Vitest 🤔 Could you share a pseudocode example?

**Review by antfu — APPROVED** [review]

**Comment by Tofandel** [comment]
Hmm, that's a bit redundant, the types of useBreakpoints where pretty much all incorrect and maybe it's better to just fix the types like in #4317 rather than introducing a computed of a ref which adds another effect scope for vue to track

File: packages/core/useMediaQuery/index.ts (hunk 1 above)
Comment (Tofandel) [reply packages/core/useMediaQuery/index.ts:61]: But in this case the effects have already triggered because it's a wrapped ref, there is no deducing or effects to track, so readonly does make more sense

**Comment by alexzhang1030** [comment]
> Hmm, that's a bit redundant, the types of useBreakpoints where pretty much all incorrect and maybe it's better to just fix the types like in #4317 rather than introducing a computed of a ref which adds another effect scope for vue to track

Nope, this is not a fix of #4272, instead, this is a fix of the behavior of `useMediaQuery`. It should not be a mutable ref here.
