### PR TITLE
fix(useElementBounding): trigger by css or style

### LINKED ISSUE #3657: useElementBounding and CSS scale cannot be used simultaneously
### Describe the bug

When I animate using scale, useElementBounding cannot capture the height. It requires other events, such as scrolling, to trigger an update.

### Reproduction

https://stackblitz.com/edit/nuxt-starter-wn8jbw?file=app.vue

### System Info

```Shell
System:
  OS: macOS 14.1.1
  CPU: (8) arm64 Apple M1
  Memory: 63.63 MB / 8.00 GB
  Shell: 3.6.4 - /opt/homebrew/bin/fish
Binaries:
  Node: 21.4.0 - /opt/homebrew/bin/node
  Yarn: 1.22.21 - /opt/homebrew/bin/yarn
  npm: 10.2.4 - /opt/homebrew/bin/npm
  pnpm: 8.12.1 - /opt/homebrew/bin/pnpm
  Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
Browsers:
  Chrome: 120.0.6099.109
  Safari: 17.1
npmPackages:
  @vueuse/nuxt: ^10.6.1 => 10.6.1
  vue: ^3.3.9 => 3.3.9
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by huiliangShen**
### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

fix #3657

### CODE REVIEW

File: packages/core/useElementBounding/index.ts [hunk 1]
```diff
@@ -91,6 +92,10 @@ export function useElementBounding(
 
   useResizeObserver(target, update)
```
Comment (Alfred-Skyblue) [inline packages/core/useElementBounding/index.ts:93]: useMutationObserver can replace useResizeObserver.

Comment (Alfred-Skyblue) [reply packages/core/useElementBounding/index.ts]: Apologies, the MutationObserver cannot observe additions to the subtree, which impacts the size of the DOM. Therefore, we cannot remove the use of ResizeObserver. You may need to roll back to the previous code.

**Review by Alfred-Skyblue — APPROVED** [review]
