### PR TITLE
fix(useCssVar): new Behavior

### LINKED ISSUE #4493: BUG | `useCssVar` | `initialValue` is not working
### Describe the bug

在复现场景中，用例1和用例2为什么不一样？从源码的角度来看，这两个用例应该是差不多的。

Why are Case 1 and Case 2 different in reproducing scenarios? From the perspective of source code, these two use cases should be similar.

### Reproduction

https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wAjAAGSbEyak9bYLY7fYgI4nAhEHGIPHDGbWZ7sLhnDFfFA-GRyBS8ADCrAiiCgf3MrBMKBu2Fk+UKKkleDArGQMPkGWhshQCKRIBRgxGYwEQmms2GbI5XMQJPJlOpG0Q2z2hwAuswjHQDMa0KAAIJgMCTBboUCpLUGCCpIgAHio2RU1iMAF4ADogTx5gB8wGAKhmXnqBwOyeGaeIhZzHBz2FT2WLpbwyD8VZrdcLz2F0iIdC1dWkKlLePFyGQikqKgONQ4sxUAHIHTdOXVEKvmyPtRxx6XM4wkom7Kf5ABZdgqkELpcr1cLXfYZujMsQSHE5szbDIcdPBULMM0QIxtHsX95AAsspTqYD-BuadZ0qbRVwoChyzqVdT08SC32wSJz10bQsI4U9tGIQxyEcLNCwnZsVFg-8pUQSYvHgbQAAM7AgbAkDQFQABJgCogxyAOLj8IOfDm2vW9UiobQIOA+jgEY2CKyjai0hA1dHlfGTm3fYZP0hRooP-cdOz8EDMzQ3RPC8JI6gMKhV1kwjiO0GyKLEmjVIY8xmLYIN2NYTieP0fjEEEkT-MQSTpM8+T+EU5TaLUjSbO08TdLXRyIlYQz7EZKsgA

### System Info

```Shell
无

None
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by ilyaliao**
resolves #4493 

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

This PR enhances several behaviors:

- Automatically adds `variable` to `window.document.documentElement` or the `target` on first use, and also when the `target element` changes.
- Allows users to change the color again in `onMounted` when setting `initialValue`.
- Adds some new `tests` to ensure that both the `state` and the `element` are indeed changed.

### CODE REVIEW

**Comment by ilyaliao** [comment]
Should this work?

```vue
<script setup lang="ts">
import { useCssVar } from '@vueuse/core'
import { ref } from 'vue'

const el = ref(null)
const color = useCssVar('--color')

function switchColor() {
  if (color.value === '#df8543')
    color.value = '#7fa998'
  else
    color.value = '#df8543'
}
</script>

<template>
  <div ref="el" style="color: var(--color)">
    Sample text, {{ color }}
  </div>
  <button @click="switchColor">
    Change Color
  </button>
</template>

```

**Comment by OrbisK** [comment]
> Should this work? If so, then this is a new bug.

Do you mean the color switch?

**Comment by YiMo1** [comment]
但是依旧没有解决`initialValue`的问题。

However, the issue of `initialValue` has not been resolved yet.

https://github.com/vueuse/vueuse/issues/4493#issuecomment-2594319783

**Comment by ilyaliao** [comment]
> > Should this work? If so, then this is a new bug.
> 
> Do you mean the color switch?

When I load the page, the color state changes to `#df8543`, but the actual element color doesn't change until the next update. This happens because `--color: #7fa998` isn't added to `window.document.documentElement` tag on the initial load.

If this isn't the expected behavior, we can fix it in this PR.

https://github.com/user-attachments/assets/1412f3d2-a7e2-4d74-81a2-d85a08031100

**Comment by ilyaliao** [comment]
> 但是依旧没有解决`initialValue`的问题。
> 
> However, the issue of `initialValue` has not been resolved yet.
> 
> [#4493 (comment)](https://github.com/vueuse/vueuse/issues/4493#issuecomment-2594319783)

對，這個 PR 主要是修復關於在 `onMounted` 中修改 `color` 狀態時未改變的問題，另一個問題如同上面我提到的，如果他不是預期行為，我們可以考慮在這個 PR 中一起修復。

Yes, this PR mainly fixes the issue where the `color` state doesn't change when modified in `onMounted`. As for the other issue, if it's not the expected behavior, we can fix it in this PR as well.

**Comment by ilyaliao** [comment]
All done.

**Review by EvgenyWas — APPROVED** [review]

File: packages/core/useCssVar/index.ts [hunk 1]
```diff
@@ -55,12 +55,12 @@ export function useCssVar(
         old[0].style.removeProperty(old[1])
       updateCssVar()
     },
-    { immediate: true },
+    { flush: 'post' },
```
Comment (OrbisK) [inline packages/core/useCssVar/index.ts:58]: dont we need both (post and immediate)? And if not why? 😄

Comment (ilyaliao) [reply packages/core/useCssVar/index.ts:58]: I think we don't need `immediate` because lines `54-55` are used to clean up the `prop` from the previous element. 

https://github.com/vueuse/vueuse/blob/0ec82c0b1737d008c6971c0b83f6320bbb76ad88/packages/core/useCssVar/index.ts#L54-L55

Initially, both old[0] and old[1] will be undefined, so `immediate: true` is unnecessary.

The reason we need `flush: 'post'` is because at line 39 `window.getComputedStyle(el).getPropertyValue(key)`

https://github.com/vueuse/vueuse/blob/0ec82c0b1737d008c6971c0b83f6320bbb76ad88/packages/core/useCssVar/index.ts#L39

if you change the `color` value at the `onMounded`, since the `color` on the `element` hasn't **really changed yet**, we won't get the **correct value** here. Therefore, we need to wait for `Vue` to update before we get the state from the element.

Comment (OrbisK) [reply packages/core/useCssVar/index.ts:58]: > both old[0] and old[1] will be empty, so immediate: true is unnecessary.

what about `updateCssVar()` to get the initial value.

Comment (ilyaliao) [reply packages/core/useCssVar/index.ts:58]: Sorry, I missed this.

I believe it's also not needed because `variable` will always equal `initialValue` at the initial. It only needs to call `updateCssVar` when subsequent changes occur.

Perhaps I'm wrong.

Comment (OrbisK) [reply packages/core/useCssVar/index.ts:58]: > Sorry, I missed this.
> 
> I believe it's also not needed because `variable` will always equal `initialValue` at the initial. It only needs to call `updateCssVar` when `variable` changes occur.
> 
> Perhaps I'm wrong.

I think if we dont do this immediate we might miss that one, no?

https://github.com/vueuse/vueuse/blob/0ec82c0b1737d008c6971c0b83f6320bbb76ad88/packages/core/useCssVar/index.ts#L38-L41

Comment (ilyaliao) [reply packages/core/useCssVar/index.ts:58]: > > Sorry, I missed this.
> > I believe it's also not needed because `variable` will always equal `initialValue` at the initial. It only needs to call `updateCssVar` when `variable` changes occur.
> > Perhaps I'm wrong.
> 
> I think if we dont do this immediate we might miss that one, no?
> 
> https://github.com/vueuse/vueuse/blob/0ec82c0b1737d008c6971c0b83f6320bbb76ad88/packages/core/useCssVar/index.ts#L38-L41

However, we have already set variable to initialValue at:

https://github.com/vueuse/vueuse/blob/0ec82c0b1737d008c6971c0b83f6320bbb76ad88/packages/core/useCssVar/index.ts#L32

In fact, in my testing, whether `immediate` is `true` or `false` doesn't affect the actual result. ofc, we can add `immediate` back first in case I missed something.

Comment (OrbisK) [reply packages/core/useCssVar/index.ts:58]: I think this should work:

```ts
  it('should have existing value', async () => {
    const vm = mount(defineComponent({
      setup() {
        const el = ref()

        const color = '--color'
        const variable = useCssVar(color, el)

        return {
          el,
          variable,
        }
      },
      template: `
        <div ref="el" style="--color: red"></div>
      `
    }))

    await nextTick()
    expect(vm.variable).toBe('red')
    expect(window.getComputedStyle(vm.el).getPropertyValue("--color")).toBe('red')
    expect(vm.el.style.getPropertyValue('--color')).toBe('red')
  })
  ```
  
  But it does'nt. `immediate` does not change the test result here. 
  
  this one does remove the `--color` from the element.
  
  https://github.com/vueuse/vueuse/blob/0ec82c0b1737d008c6971c0b83f6320bbb76ad88/packages/core/useCssVar/index.ts#L61-L72

Comment (ilyaliao) [reply packages/core/useCssVar/index.ts:58]: Oh...It seems quite tricky, thank you for noticing.

I need some time to study it.

**Comment by ilyaliao** [comment]
I believe I have completed the task. I made some minor modifications, which are smaller than before but still resolved the issue. Additionally, I added more tests to ensure the original behavior remains intact. 

Please lmk if I missed anything :)

File: packages/core/useCssVar/index.ts [hunk 2]
```diff
@@ -55,12 +55,11 @@ export function useCssVar(
...
       updateCssVar()
     },
-    { immediate: true },
   )
 
   watch(
-    variable,
-    (val) => {
+    [variable, elRef],
+    ([val]) => {
```
Comment (OrbisK) [inline packages/core/useCssVar/index.ts:62]: Maybe not such a big difference, but I think we should add the new element here as well?
```suggestion
    [variable, elRef],
    ([val, el]) => {
```

I can't suggest the full function because it's not considered a change. So the function should use el too. 😄 what do you think?

Comment (ilyaliao) [reply packages/core/useCssVar/index.ts:62]: Sure, no problem, I think it's great.

**Review by OrbisK — APPROVED** [review]

**Comment by OrbisK** [comment]
@ilyaliao isnt this a fix of the initial value instead of new behavior?

**Comment by ilyaliao** [comment]
> @ilyaliao isnt this a fix of the initial value instead of new behavior?

At first it was like this, but later I also `added`/`modified` some other features.
