### PR TITLE
fix(types): allow async functions in useDebounceFn and useThrottleFn

### LINKED ISSUE #4082: useDebounceFn should support accepting functions that return promises as well as void
### Describe the bug

When using [@typescript-eslint/no-misused-promises](https://typescript-eslint.io/rules/no-misused-promises) you will get `Promise returned in function argument where a void return was expected` whenever you try to pass a function that returns a promise (like an async function).

image

### Reproduction

none

### System Info

```Shell
System:
    OS: Linux 6.9 Arch Linux
    CPU: (16) x64 AMD Ryzen 9 PRO 7940HS w/ Radeon 780M Graphics
    Memory: 10.26 GB / 58.64 GB
    Container: Yes
    Shell: 5.2.26 - /bin/bash
  Binaries:
    Node: 20.14.0 - /run/user/1000/fnm_multishells/165113_1719820994869/bin/node
    Yarn: 4.3.1 - /run/user/1000/fnm_multishells/165113_1719820994869/bin/yarn
    npm: 10.7.0 - /run/user/1000/fnm_multishells/165113_1719820994869/bin/npm
    Watchman: 20240414.112832.0 - /usr/bin/watchman
  Browsers:
    Chromium: 126.0.6478.126
  npmPackages:
    @vueuse/core: ^10.11.0 => 10.11.0 
    @vueuse/integrations: ^10.11.0 => 10.11.0 
    vue: ^3.4.31 => 3.4.31
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by xiaoxiaohuayu**
### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description
Resolve #4082 
Fixes TypeScript ESLint warning when passing async functions to [useDebounceFn](file:///Volumes/M2/vueuse/packages/shared/useDebounceFn/index.ts#L18-L27) and [useThrottleFn](file:///Volumes/M2/vueuse/packages/shared/useThrottleFn/index.ts#L23-L34).

When using the `@typescript-eslint/no-misused-promises` rule, passing async functions (or any function returning a Promise) to [useDebounceFn](file:///Volumes/M2/vueuse/packages/shared/useDebounceFn/index.ts#L18-L27) or [useThrottleFn](file:///Volumes/M2/vueuse/packages/shared/useThrottleFn/index.ts#L23-L34) triggers the following warning:

### Additional context

```typescript
// Before
export type FunctionArgs<Args extends any[] = any[], Return = void> = (...args: Args) => Return

// After  
export type FunctionArgs<Args extends any[] = any[], Return = any> = (...args: Args) => Return

### CODE REVIEW

File: packages/shared/utils/filters.ts [hunk 1]
```diff
@@ -4,7 +4,7 @@ import { isRef, readonly, toValue } from 'vue'
 import { toRef } from '../toRef'
 import { noop } from './is'
 
-export type FunctionArgs<Args extends any[] = any[], Return = void> = (...args: Args) => Return
+export type FunctionArgs<Args extends any[] = any[], Return = any> = (...args: Args) => Return
```
Comment (OrbisK) [inline packages/shared/utils/filters.ts]:
```suggestion
export type FunctionArgs<Args extends any[] = any[], Return = unknown> = (...args: Args) => Return
```

**Review by OrbisK — CHANGES_REQUESTED** [review]

File: packages/shared/utils/filters.ts (hunk 1 above)
Comment (xiaoxiaohuayu) [reply packages/shared/utils/filters.ts]: Thank you, doing it this way is indeed better.
