### PR TITLE
fix(useScroll): add `onError` hook and avoid throws by default, fix #3580

### LINKED ISSUE #3580: useScroll is broken in version 10.6.0
### Describe the bug

In version `1.6.0` useScroll is not working.
```log
index.mjs:3859 Uncaught (in promise) TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at setArrivedState (index.mjs:3859:40)
```
Снимок экрана 2023-11-22 в 19 57 07

Снимок экрана 2023-11-22 в 19 57 25

This is what was working in version `1.5.0`:
```js
const { arrivedState } = useScroll(scrollBox)
const { bottom, top } = toRefs(arrivedState)
```
Looks like this MR broke the functionality:
https://github.com/vueuse/vueuse/pull/3384

___
In my reproduction the error is another (maybe because it's not nuxt) but it also does not work

### Reproduction

https://codesandbox.io/p/devbox/wild-smoke-qvhhq2?file=%2Fpages%2Findex.vue%3A3%2C9&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpa4yb7h00064e6j4kztga01%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpa4yb7h00034e6jtv0mmnoz%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpa4yb7h00044e6jqqynzs4w%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpa4yb7h00054e6jpvtxv7nk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B53.13247702202947%252C46.86752297797053%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpa4yb7h00034e6jtv0mmnoz%2522%253A%257B%2522id%2522%253A%2522clpa4yb7h00034e6jtv0mmnoz%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpa5i4v600034e6j2bl0orry%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A3%252C%2522startColumn%2522%253A9%252C%2522endLineNumber%2522%253A3%252C%2522endColumn%2522%253A9%257D%255D%252C%2522filepath%2522%253A%2522%252Fpages%252Findex.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpa5i4v600034e6j2bl0orry%2522%257D%252C%2522clpa4yb7h00054e6jpvtxv7nk%2522%253A%257B%2522id%2522%253A%2522clpa4yb7h00054e6jpvtxv7nk%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clpa5f8rc00f34e6j13jfona1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpa5f8rc00f34e6j13jfona1%2522%257D%252C%2522clpa4yb7h00044e6jqqynzs4w%2522%253A%257B%2522id%2522%253A%2522clpa4yb7h00044e6jqqynzs4w%2522%252C%2522activeTabId%2522%253A%2522clpa4zctl008e4e6jq0hlxn96%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpa4zctl008e4e6jq0hlxn96%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clpa4zcwb000wefbchkxmhpv5%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### System Info

```Shell
System:
    OS: macOS 13.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 49.66 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.1 - ~/.nvm/versions/node/v20.8.1/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.8.1/bin/npm
    pnpm: 8.10.5 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 16.6
  npmPackages:
    @vueuse/nuxt: 10.6.1 => 10.6.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by steklopod**
### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

- Attemp to fix this
https://github.com/vueuse/vueuse/issues/3580

- Bug appeared here:
https://github.com/vueuse/vueuse/pull/3384

### Additional context
image

### CODE REVIEW

File: packages/core/useScroll/index.ts [hunk 1]
```diff
@@ -251,11 +251,15 @@ export function useScroll(
...
-    setArrivedState(_element)
+    try {
+      const _element = toValue(element)
+      if (!_element)
+        return
+      setArrivedState(_element)
+    }
+    catch (e) {
+      // console.debug('Error setting ArrivedState for useScroll function')
+    }
```
[the remark this answers is not in the document]
Comment (antfu) [reply packages/core/useScroll/index.ts:270]: Thanks. But the first thing is how would the error get triggered here?

**Comment by xandao-dev** [comment]
I don't think that this is fixing the issue. The error happens when we use a component ref instead of a dom element ref.

File: packages/core/useScroll/index.ts [hunk 2]
```diff
@@ -251,11 +259,15 @@ export function useScroll(
   )
 
   tryOnMounted(() => {
-    const _element = toValue(element)
-    if (!_element)
-      return
-
-    setArrivedState(_element)
+    try {
+      const _element = toValue(element)
```
Comment (brendomaciel) [inline packages/core/useScroll/index.ts:263]:
```suggestion
      const _element = unrefElement(element)
```

Comment (steklopod) [reply packages/core/useScroll/index.ts]: Could be the root of the problem 🤔

File: packages/core/useScroll/index.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (steklopod) [reply packages/core/useScroll/index.ts:270]: Looks like the root of the problem was highlighted by **brendomaciel**  👇🏻https://github.com/vueuse/vueuse/pull/3605#discussion_r1439898056

File: packages/core/useScroll/index.ts (hunk 2 above)
Comment (brendomaciel) [reply packages/core/useScroll/index.ts]: Yes. Sorry for the lack of explanation.

The problem occurs because the `ref` value itself is a component instance when it's being used in components (refer to [documentation](https://vuejs.org/guide/essentials/template-refs.html#ref-on-component)), so the `toValue` is just unwrapping it (as expected). Since  `getComputedStyle` doesn't exist on the instance object, an error is thrown.

Luckily, VueUse already have something to handle this, the `unrefElement` that I used in the suggestion.

**Comment by Blackfaded** [comment]
Can this PR be reviewed? We are facing the same issue if the component is a vue component and not a plain dom node.

**Review by antfu — DISMISSED** [review]

**Review by antfu — APPROVED** [review]

**Review by antfu — APPROVED** [review]
