### PR TITLE
fix(syncRef): avoid infinite sync

### LINKED ISSUE #3289: syncRef custom  Maximum call stack size exceeded
### Describe the bug

use custom transform ,  just like demo : https://vueuse.org/shared/syncRef/
```
import { syncRef } from '@vueuse/core'

const a = ref(10)
const b = ref(2)
const stop = syncRef(a, b, {
  transform: {
    ltr: left => left * 2,
    rtl: right => right / 3  // got error : Maximum call stack size exceeded
  }
})

```

watching left and right immediate,  They influence each other

### Reproduction

https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wAjAAGSbEyak9bYLY7fYgI4nAhEHGIPHDGbWZ7sLhnDFfFA-GRyBS8ADCrAiiCgf3MrBMKBu2Fk+UKKkleDArGQMPkGWhshQCKRIBRgxGYwEQmms2GbI5XMQJPJlOpG0Q2z2hwAuswjHQDMa0KAAIJgMCTBboUCpLUGCCpIjPYXSIh0LV1aQqYAqZAhWwAJUQJgONQ4sxUAHIHTdOXVEFWADpZTMcbPAaxGMtGCt4asLZu2eTIbOuAC8Ki72jJ9hbM2wo5UpRUk+njTn2HnI+zo+8q7zBagxaM2ggjGXF+ALZU8Qqi9qHDwaBzN9vKgM0g4L6DRmz44APg-EtswAKhURpGDfW92wMF9JHgPpVyAhCkOGDo3wOFsDk3bdFylRBJi8eAzyjQxyEYUoyIMch7EZZhJTqKgzETQjoxDEA4zABMk14AAeZjiDfWoVXHJsQDweRWHEt9SngMSQCCRDpAoABWUlSTcSoYDQKhtLUjSZPMGog02BSAD8VBmAwjNvVJNmkBTuBVRAOFslQwAUxp3NKJjXIUit+BoKgjIAt8+OQSBzHsxzxIAFk2GyQAA4Bc2Ici0gOA4+LuKKwuMiKoviT1YpYfs9I4HSlL6CgAE4NK0yq0G8aBghCAzxJUPAFJU7zkoAWXYSFUo-CBSk8FQspyyKIGwfKcsEgCU0kGQiBoANsEQAAFCtBm0a9jITca4JUAEv18KDjPSmjEBfAA5Ug8HGjhLpwxksqAA

### System Info

```Shell
windows, Chrome/114.0.0.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by chaii3**
#fixes #3289

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Additional context

---

### <samp>🤖 Generated by Copilot at 76294db</samp>

This pull request improves the `syncRef` function and its test case. It uses `pausableWatch` to avoid circular updates when syncing refs with mutual convertors, and it tests more realistic scenarios for the convertor functions. It also refactors the `syncRef` code for readability and consistency.

### <samp>🤖 Generated by Copilot at 76294db</samp>

*  Use `pausableWatch` instead of `watch` to sync refs with mutual convertors and avoid circular updates ([link](https://github.com/vueuse/vueuse/pull/3312/files?diff=unified&w=0#diff-4d06ccb8d3aefeb967955e826b907fb164dcc8e10889f6e48b03792ae45c3d1eL1-R3), [link](https://github.com/vueuse/vueuse/pull/3312/files?diff=unified&w=0#diff-4d06ccb8d3aefeb967955e826b907fb164dcc8e10889f6e48b03792ae45c3d1eL50-R53), [link](https://github.com/vueuse/vueuse/pull/3312/files?diff=unified&w=0#diff-4d06ccb8d3aefeb967955e826b907fb164dcc8e10889f6e48b03792ae45c3d1eL57-R65), [link](https://github.com/vueuse/vueuse/pull/3312/files?diff=unified&w=0#diff-4d06ccb8d3aefeb967955e826b907fb164dcc8e10889f6e48b03792ae45c3d1eL65-R77), [link](https://github.com/vueuse/vueuse/pull/3312/files?diff=unified&w=0#diff-4d06ccb8d3aefeb967955e826b907fb164dcc8e10889f6e48b03792ae45c3d1eL73-R84), [link](https://github.com/vueuse/vueuse/pull/3312/files?diff=unified&w=0#diff-00f6d1bad81095b21247b8aeef7ed3fef414bd55869280b7a144a87b5613cc4fL54-R59))
*  Modify the test case for `syncRef` with mutual convertors in `packages/shared/syncRef/index.test.ts` to use different initial values and transform functions, and assert the expected values after sync and change ([link](https://github.com/vueuse/vueuse/pull/3312/files?diff=unified&w=0#diff-00f6d1bad81095b21247b8aeef7ed3fef414bd55869280b7a144a87b5613cc4fL65-R65), [link](https://github.com/vueuse/vueuse/pull/3312/files?diff=unified&w=0#diff-00f6d1bad81095b21247b8aeef7ed3fef414bd55869280b7a144a87b5613cc4fL73-R73))
*  Add a comment to document the `options` parameter for the `syncRef` function in `packages/shared/syncRef/index.ts` ([link](https://github.com/vueuse/vueuse/pull/3312/files?diff=unified&w=0#diff-4d06ccb8d3aefeb967955e826b907fb164dcc8e10889f6e48b03792ae45c3d1eR41))

### CODE REVIEW

File: packages/shared/syncRef/index.ts [hunk 1]
```diff
@@ -49,38 +47,46 @@ export function syncRef<L, R = L>(left: Ref<L>, right: Ref<R>, options: SyncRefO
...
   if (direction === 'both' || direction === 'ltr') {
-    watchLeft = pausableWatch(
+    watchLeft = watch(
       left,
       (newValue) => {
-        watchRight?.pause()
+        if (stop)
+          return
+
+        stop = true
```
Comment (nothing-sy) [inline packages/shared/syncRef/index.ts:65]: If the flush paramter of options is 'post', dose it work normally?
