### PR TITLE
fix(useThrottleFn): check negative timeout

### LINKED ISSUE #2618: UseThrottleFn does not call function - completely broken
### Describe the bug

In version 9.9.0 this function works

  const ZoomToPointsThrottled = useThrottleFn(
    (force: boolean) => {
      ZoomToPoints(force);
    },
    1500,
    true,
    false
  );

In version 9.10.0 the ZoomToPoints function is never called.  I tried removing the "force" parameter from both the throttle and the called functions, but this made no difference.

Problem seems to have been introduced in pull request: https://github.com/vueuse/vueuse/pull/2580

Rolling back to 9.9.0 fixes the problem for me.

The same can be seen in the linked reproduction project.  The "Increment Throttled" button works in 9.9.0 but not in 9.10.0

### Reproduction

https://stackblitz.com/edit/vitejs-vite-bjrjmi/?file=package.json,src%2FApp.vue

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 658.50 MB / 15.69 GB
  Binaries:
    Node: 16.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.2.0 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.46)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vueuse/core: 9.10.0 => 9.10.0
    vue: 3.2.45 => 3.2.45
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by vaakian**
### Description

fixes #2618 

### Additional context

caused by a **BIG** negative timeout. Exists in the past versions as well, but only occurs at the first call.
```js
const printHello = () => console.log('hello')
// will not print `hello`
setTimeout(printHello, -1672930567173)

// will print `hello`
setTimeout(printHello, -167293056)
```

---

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Review by wheatjs — APPROVED** [review]

File: packages/shared/utils/filters.ts [hunk 1]
```diff
@@ -160,14 +160,16 @@ export function throttleFilter(ms: MaybeComputedRef<number>, trailing = true, le
...
+
+      lastValue = new Promise((resolve, reject) => {
         lastRejector = rejectOnCancel ? reject : resolve
         timer = setTimeout(() => {
           lastExec = Date.now()
           isLeading = true
           resolve(invoke())
           clear()
-        }, duration - elapsed)
+        }, timeout > 0 ? timeout : 0)
```
Comment (webfansplz) [inline packages/shared/utils/filters.ts:172]: Math.max(0,duration - elapsed)

**Comment by shrpne** [comment]
@vaakian can you update your PR please?
