### PR TITLE
fix(onClickOutside): the order of overload signatures

### LINKED ISSUE #4838: BUG | `onClickOutside` | breaking change + wrong type declaration regarding the use of `controls`
### Describe the bug

Type declaration for `onClickOutside` is: 
```ts
declare function onClickOutside(target: MaybeElementRef, handler: OnClickOutsideHandler<{
    detectIframe: OnClickOutsideOptions['detectIframe'];
    controls: true;
}>, options: OnClickOutsideOptions<true>): {
    stop: Fn;
    cancel: Fn;
    trigger: (event: Event) => void;
};
declare function onClickOutside(target: MaybeElementRef, handler: OnClickOutsideHandler<{
    detectIframe: OnClickOutsideOptions['detectIframe'];
    controls: false;
}>, options?: OnClickOutsideOptions<false>): Fn;
```

But in [the source,](https://github.com/vueuse/vueuse/blob/main/packages/core/onClickOutside/index.ts#L30) `controls` is optional. Please note that `Fn` was the return type of this function before the introduction of `controls`. Now, if `controls === true` the return type is an object, if `controls === undefined` or `controls === false` it’s a `Fn`.

The type declaration makes it so that by leaving `controls` blank (even though this is the default), the return type is broken. TypeScript tells me that it’s ok to use `.stop` on the return type (when it is, in fact, a `Fn`), so when you call `stop()`, the code breaks.

### Reproduction

https://playground.vueuse.org/#eNqNU0Fu2zAQ/MpWF9uoZbttDkUqGWmDHFIUTZH4qIssrRQ6FEmQlO1A0N+7pCRHddqgPhjUznA4nF02wVelFvsag8sgMplmyoJBWyvgqSjjJLAmCdaJYJWS2kIDUlxzlj3d1dawHKGFQssKJlckURtcZlLjZESn2gYrxVOL91ic6MSefBnR9GssEZkUxkIma2EhdpTpakZAV0aRbjnmPWB1jQ4b0AaMlYok4zPD0z8NTSeZAzepLtFOZnOYziBed2cu9imvEd7H8GEOTdvJF7XILJPC6/9gxqJgoqRdTSLAF6eOCIO/XiSGIuUGCWkTES27oClW+rC9G/oCiHK2h4ynxlD0BccjuL8wkxzKVIUXwIhuwgyFRQ272lhWPA+fh5B0EQU89gvfOaBftK2tJdOD8rYMS50+h59XK1DhR9B03xzzEx/AZwYVvusFlp3CoOdsUu4kNcovCf7fuitspc5p+frwSK1v4ZAakiNxarLsp00W0DS+OW0LllVoFtFSvezrr7kPmbPWt2Bk65/3hit/FFHO+kquHtwk8aF0nsSSouha16+i5aijwZweEI1kwcrFzkhBr8wPCuUmK8U46jvlxoke2WU3Qg5LOZeH777mBns+1LNHzJ7+Ut+Zo6slwS+NBvUek+CE2b41Dr55+IlHWp/ASuY1J/Yb4D0ayWvnsaN9o8TI9ojn3d76l0z5bMzNkZIyw6WcUcdsPT8J6HVfv3H1F7ufFhd+Hz2ZoP0NTOiQ9A==

### System Info

```Shell
System:
    OS: Windows 11 10.0.26100
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 2.89 GB / 15.73 GB
  Binaries:
    Node: 22.14.0 - C:\nvm4w\nodejs\node.EXE
    npm: 11.1.0 - C:\nvm4w\nodejs\npm.CMD
    pnpm: 8.1.1 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (130.0.2849.68)
    Internet Explorer: 11.0.26100.1882
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vueuse.org/guide).
- [x] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by whiteyebrw**
### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [ ] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [ ] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

Fixes #4838.
The order of Overload Signatures has been changed.

### CODE REVIEW

File: packages/core/onClickOutside/index.ts [hunk 1]
```diff
@@ -53,18 +53,18 @@ let _iOSWorkaround = false
...
   handler: OnClickOutsideHandler<{ detectIframe: OnClickOutsideOptions['detectIframe'], controls: false }>,
   options?: OnClickOutsideOptions<false>,
 ): Fn
 
+export function onClickOutside(
+  target: MaybeElementRef,
+  handler: OnClickOutsideHandler<{ detectIframe: OnClickOutsideOptions['detectIframe'], controls: true }>,
+  options: OnClickOutsideOptions<true>,
+): { stop: Fn, cancel: Fn, trigger: (event: Event) => void }
+
```
Comment (rzzf) [inline packages/core/onClickOutside/index.ts]: Would you be able to assist with solving this kind of type inference issue as well? I’d really appreciate it!

```ts
onClickOutside(document.documentElement, (e) => {
  // Currently, the type of e is `Event | PointerEvent`
  // The correct type should be `Event | PointerEvent | FocusEvent`.
}, {
  controls: true,
  detectIframe: true
})
```

Comment (whiteyebrw) [reply packages/core/onClickOutside/index.ts]: ok. i'll see what i can do.

Comment (whiteyebrw) [reply packages/core/onClickOutside/index.ts]: I had to add stricter overloads for the handler.

**Comment by 43081j** [comment]
i think you could simplify this to two overloads 👀 

you only need to know what `controls` is in the overloads so you can get the right return type

so we could instead do something like this:

```ts
export function onClickOutside<
  T extends OnClickOutsideOptions<true>
>(
  target: MaybeElementRef,
  handler: OnClickOutsideHandler<T>,
  options: T
): Controls;
export function onClickOutside<
  T extends OnClickOutsideOptions<false>
>(
  target: MaybeElementRef,
  handler: OnClickOutsideHandler<T>,
  options: T
): Fn;
```

and

```ts
export type OnClickOutsideHandler<
  TControls extends boolean, // may not be needed? may be able to just do `<boolean>` below
  T extends OnClickOutsideOptions<TControls>
> = (
  event: (T['detectIframe'] extends true ? FocusEvent : never)
    | (T['controls'] extends true ? Event : never)
    | PointerEvent,
) => void
```

**Review by ilyaliao — APPROVED** [review]
