### PR TITLE
fix(useAxios): use shallowRef for resposne, data, and error

### LINKED ISSUE #415: useAxios: use shallowRef for response, data and error
Could [useAxios](https://github.com/vueuse/vueuse/blob/3e14ee39f94ceac4bc9684df456f5e41eb076cca/packages/integrations/useAxios/index.ts#L24) be modified to use [shallowRef](https://v3.vuejs.org/api/refs-api.html#shallowref) for [response](https://github.com/vueuse/vueuse/blob/3e14ee39f94ceac4bc9684df456f5e41eb076cca/packages/integrations/useAxios/index.ts#L45), [data](https://github.com/vueuse/vueuse/blob/3e14ee39f94ceac4bc9684df456f5e41eb076cca/packages/integrations/useAxios/index.ts#L46) and [error](https://github.com/vueuse/vueuse/blob/3e14ee39f94ceac4bc9684df456f5e41eb076cca/packages/integrations/useAxios/index.ts#L50)?

## Rationale

`shallowRef` would improve performance because `response`, `data` and `error` would not be made deeply reactive. If the content of `response.value`, `data.value` and `error.value` are not modified (which for me is the best practice), then making them reactive is completely redundant. The client code developers could explicitly decide, if they want to make the values of those refs deeply reactive using [reactive](https://v3.vuejs.org/api/basic-reactivity.html#reactive) or [ref](https://v3.vuejs.org/api/refs-api.html#ref).

### PR DESCRIPTION
**Pull request by wheatjs**
Fixes #415

### CODE REVIEW

File: packages/integrations/useAxios/index.ts [hunk 1]
```diff
@@ -42,12 +42,12 @@ export function useAxios<T = any>(url: string, ...args: any[]) {
       instance = args[1]
   }
 
-  const response = ref<any>(null) as Ref<AxiosResponse<T> | undefined>
-  const data = ref<any>(undefined) as Ref<T | undefined>
+  const response = shallowRef<any>(null) as Ref<AxiosResponse<T> | undefined>
```
Comment (antfu) [inline packages/integrations/useAxios/index.ts:45]:
```suggestion
  const response = shallowRef<AxiosResponse<T> | null>(null)
```

Shouldn't we do this? Typed as undefined but passed as null feels a bit weird to me.

Comment (wheatjs) [reply packages/integrations/useAxios/index.ts]: Ah yeah haha, not sure what was up with the types there to begin with 😅

File: packages/integrations/useAxios/index.ts [hunk 2]
```diff
@@ -42,12 +42,12 @@ export function useAxios<T = any>(url: string, ...args: any[]) {
       instance = args[1]
   }
 
-  const response = ref<any>(null) as Ref<AxiosResponse<T> | undefined>
-  const data = ref<any>(undefined) as Ref<T | undefined>
+  const response = shallowRef<any>(null) as Ref<AxiosResponse<T> | null>
+  const data = shallowRef<any>(null) as Ref<T | null>
```
Comment (antfu) [inline packages/integrations/useAxios/index.ts:46]: Since shalowRef does not unwrap, can we just have the type in the generic?

Comment (wheatjs) [reply packages/integrations/useAxios/index.ts:46]: Hmm I'm not quite sure what you mean. I did what I thought you were talking about above but maybe that was a misunderstanding? Could we just do something like `const response = shallowRef<AxiosResponse<T>>()`

File: packages/integrations/useAxios/index.ts [hunk 3]
```diff
@@ -42,12 +42,12 @@ export function useAxios<T = any>(url: string, ...args: any[]) {
       instance = args[1]
   }
 
-  const response = ref<any>(null) as Ref<AxiosResponse<T> | undefined>
-  const data = ref<any>(undefined) as Ref<T | undefined>
+  const response = shallowRef<AxiosResponse<T>>()
```
Comment (gkubisa) [inline packages/integrations/useAxios/index.ts:45]: Should it be `const response = shallowRef<AxiosResponse<T> | undefined>()`?

Comment (wheatjs) [reply packages/integrations/useAxios/index.ts:45]: image
It is since `shallowRef`'s signature is `export declare function shallowRef<T = any>(): Ref<T | undefined>;`

Comment (antfu) [reply packages/integrations/useAxios/index.ts:45]: It's because you didn't pass the default value

```ts
const response = shallowRef<AxiosResponse<T> | null>(null)
```

Comment (wheatjs) [reply packages/integrations/useAxios/index.ts:45]: I was going with the original typing that the functions had. Did you want them to be null instead of undefined?

Comment (antfu) [reply packages/integrations/useAxios/index.ts:45]: Both work to me

**Review by antfu — APPROVED** [review]
