### PR TITLE
fix(useWebSocket): don't call close() on pongTimeout if connection al…

### LINKED ISSUE #4607: BUG | `useWebSocket ` | autoReconnect is not working when pongTimeout is set
### Describe the bug

The WebSocket fails to auto reconnect when a `pongTimeout` is set and the server closes the connection.
It's because in the heartbeat `useIntervalFn()`, the `pongTimeoutWait` always calls `close()` which resets the `retryTimeout`. It should only call close if the connection if not already closed.

### Reproduction

https://github.com/Azurency/vueuse-websocket-heartbeat-close-reproduction

### System Info

```Shell
System:
    OS: macOS 15.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 130.53 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 23.7.0 - ~/.nvm/versions/node/v23.7.0/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 10.9.2 - ~/.nvm/versions/node/v23.7.0/bin/npm
    pnpm: 9.1.0 - /usr/local/bin/pnpm
    bun: 1.0.10 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 108.1.46.144
    Edge: 131.0.2903.70
    Safari: 18.3
  npmPackages:
    @vueuse/core: ^12.7.0 => 12.7.0 
    vue: ^3.5.13 => 3.5.13
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vueuse.org/guide).
- [x] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by Azurency**
### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

Fixes #4607. 
- Only call `close()` in `pongTimeoutWait` is the connection is not `CLOSED`

### Additional context

- I tried to add some tests for the heartbeat

### CODE REVIEW

**Comment by ilyaliao** [comment]
Would it be better if we reset the `heartbeat` when `ws.onclose` occurs?

**Comment by Azurency** [comment]
Yes, it would also fix the issue. And it might be cleaner to stop sending the heartbeat in `ws.onclose` directly.

File: packages/core/useWebSocket/index.ts [hunk 1]
```diff
@@ -247,6 +247,8 @@ export function useWebSocket<Data = any>(
 
     ws.onclose = (ev) => {
       status.value = 'CLOSED'
+      resetHeartbeat()
+      heartbeatPause?.()
```
Comment (ilyaliao) [inline packages/core/useWebSocket/index.ts:251]: Should only need `resetHeartbeat`?

Comment (Azurency) [reply packages/core/useWebSocket/index.ts:251]: It does need `heartbeatPause?.()`, otherwise the issue is just delayed until the next heartbeat interval that will recreate the `pongTimeoutWait` and call close after the timeout (and clear the retry, etc.). 
I added a unit test for this _"should not call close on pongTimeout if connection already closed"_ you can try to remove `heartbeatPause?.()` and see  that `close()` if still called.

Comment (ilyaliao) [reply packages/core/useWebSocket/index.ts:251]: Yes, I got it mixed up

**Review by antfu — APPROVED** [review]
