### PR TITLE
fix(useMouseInElement): check if mouse out of window

### LINKED ISSUE #2454: useMouseInElement still thinks mouse is within element when leaving the browser window
### Describe the bug

If using the useMouseInElement composable on an element bordering the edge of the browser window, transitioning the mouse directly from hovering over the element to outside the browser window does not update the composable's state as one would assume.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-jegj7g?file=src/App.vue

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 569.16 MB / 15.73 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 107.0.5304.107
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.42)  
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vueuse/core: ^9.4.0 => 9.4.0 
    vue: ^3.0.0 => 3.2.41
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by chaii3**
fixes #2454

### Additional context

---

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Review by syy11cn — COMMENTED** [review]
It seems the `import` statement prefers not to include `index` in path. 👇 

https://github.com/vueuse/vueuse/blob/main/packages/core/useMouseInElement/index.ts#L3

What about considering to modify the import path?

```diff
- import { useEventListener } from '../useEventListener/index'
+ import { useEventListener } from '../useEventListener'
```

File: packages/core/useMouseInElement/index.ts [hunk 1]
```diff
@@ -4,6 +4,7 @@ import { unrefElement } from '../unrefElement'
 import type { UseMouseOptions } from '../useMouse'
 import { useMouse } from '../useMouse'
 import { defaultWindow } from '../_configurable'
+import { useEventListener } from '../useEventListener/index'
```
Comment (antfu) [inline packages/core/useMouseInElement/index.ts:7]:
```suggestion
import { useEventListener } from '../useEventListener'
```
