### PR TITLE
fix(until): `.not` returns new instance

### LINKED ISSUE #2223: `until.not` is not implemented correctly
### Describe the bug

Currently `until().not` is a getter which toggles the internal state and returns self. It will cause problems if the user store the result of `until()` in a variable and use `.not` more than once, e.g.:
```ts
const a = ref(false);
const u = until(a);
u.not.toBeTruthy().then(() => console.log('ok1'));
u.not.toBeTruthy().then(() => console.log('ok2'));
```

We expect both `ok1` and `ok2` will be output but in fact `ok2` is not.

### Reproduction

https://stackblitz.com/edit/vue-zhcbnm?file=src%2Fcomponents%2FHelloWorld.vue,src%2FApp.vue

### System Info

```Shell
System:
    OS: macOS 12.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.14.2
    npm: 8.5.0
  Browsers:
    Chrome: 105.0.5195.125
    Safari: 15.1
  npmPackages:
    @vueuse/core: ^8.6.0 => 8.6.0 
    @vueuse/shared: ^8.6.0 => 8.6.0 
    vue: 2.7.10 => 2.7.10
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by lsdsjy**
### Description

Fixes #2223 

### Additional context

---

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by antfu** [comment]
Can we have some tests for it? Thanks

File: packages/shared/until/index.ts [hunk 1]
```diff
@@ -66,24 +66,7 @@ export interface UntilArrayInstance<T> extends UntilBaseInstance<T> {
...
- *
- * alert('Counter is now larger than 7!')
- * ```
- */
-export function until<T extends unknown[]>(r: WatchSource<T> | MaybeComputedRef<T>): UntilArrayInstance<T>
-export function until<T>(r: WatchSource<T> | MaybeComputedRef<T>): UntilValueInstance<T>
-export function until<T>(r: any): any {
-  let isNot = false
-
+export function _until<T>(r: any, isNot = false): any {
```
Comment (antfu) [inline packages/shared/until/index.ts:69]: We should not expose it

**Review by antfu — APPROVED** [review]
