### PR TITLE
fix(createEventHook): `trigger` should not ignore falsy values

### LINKED ISSUE #3560: `createEventHook` won't pass falsy values into `on` handlers
### Describe the bug

When passing falsy values into `trigger` function of `createEventHook` these won't be correctly passed to `on` handlers.

Got broken in this PR: https://github.com/vueuse/vueuse/pull/3507

Unfortunately check in `trigger` function will ignore all falsy parameters. Should probably be more explicit and check against `undefined`.
https://github.com/vueuse/vueuse/blob/656fe54c7d8357e605917c055b52a1c1bf34a554/packages/shared/createEventHook/index.ts#L42

### Reproduction

https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERhmesRNk5uIgBRTdSOXB7mbt7+wYjMYCITTWbDS7ka63e6Ic4ARgADJMAGyTeHrbBbHb7EBHE4EIiQxDQ4bIfTWKiPdhcM7vT7fLocHq8PoDIajcagmZzYmk8mVRBUBHItEYjaIbZ7Q4AXWYRjoBhQ6FAAEEwGBJgsVSBUngwAYIKkiAAeKjZAB8AB1zCoTaUAglzKEwIgALxWkAO-ryT0qc5QIKwD26yTwJAcbSI+yei0ABQgyGcAHJEcmTcNvU7rbb7Rwcyo7Vn5PEQq6Q8XsH6A0GYCHpGGI9ojIYbjGQPHEymWwYbunM475AWi-VhsP7YPnWX3Z7K9XA3Rg56G3Rw4hI9hSBF252kypk5uIv3K+PyioxzaACqN9dCtAqYDAeI3ykqA4HG2FvPnnMAJUQ3DEHQd4Pk+1jcNkQpvh+ubDOaxAWo8EhSNIRB0PqdTSA+KgSIgRqIK8HjYNIAASrCsDAb41Bwsz7nyNx3HUiDJja6FgJh2HWCYBzUbRyYLMmADcNozNgyBYU+K5rhwjAqCWPFujh1j4YRNikeRMDaPYwlVrY8jiSo4GIJBVAqIpXFaTpokGVJEZQeZiBGFG2k2ja8jaNoxCGOQjhuhaD6fs+q52VQWreYgADUEU6YWRkmWFBiqIpXmJYgOkHNpeLvkAA

### System Info

```Shell
System:
    OS: macOS 14.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 186.45 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - /usr/local/bin/node
    Yarn: 4.0.1 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
    bun: 1.0.6 - ~/.bun/bin/bun
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 17.1
  npmPackages:
    @vueuse/components: ^10.6.1 => 10.6.1 
    @vueuse/core: ^10.6.1 => 10.6.1 
    @vueuse/integrations: ^10.6.1 => 10.6.1 
    vue: ^3.3.8 => 3.3.8
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by romansp**
### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description
Fixes #3560.

---

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at d80046c</samp>

This pull request fixes a bug and adds a test case for the `createEventHook` function. It allows passing falsy values to the event hook callbacks and checks the expected results in the test file `packages/shared/createEventHook/index.test.ts`.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at d80046c</samp>

* Fix a bug and improve the flexibility of the `trigger` function in `createEventHook` ([link](https://github.com/vueuse/vueuse/pull/3561/files?diff=unified&w=0#diff-e7f6c2121aa36ff115952572f25b671a5cc7549c37f2fab6dda05029cd65dbe2L42-R42))
* Add a new test case for the `createEventHook` function to check the behavior of the `trigger` function with falsy values ([link](https://github.com/vueuse/vueuse/pull/3561/files?diff=unified&w=0#diff-25029db94c761070c7346023ff0f43b38cf34bbfe14be3c81bbf17c751ecbac3R42-R60))

### CODE REVIEW

File: packages/shared/createEventHook/index.ts [hunk 1]
```diff
@@ -39,7 +39,7 @@ export function createEventHook<T = any>(): EventHook<T> {
   }
 
   const trigger: EventHookTrigger<T> = (param?: T) => {
-    return Promise.all(Array.from(fns).map(fn => param ? fn(param) : (fn as Callback<void>)()))
+    return Promise.all(Array.from(fns).map(fn => param !== undefined ? fn(param) : (fn as Callback<void>)()))
```
Comment (Alfred-Skyblue) [inline packages/shared/createEventHook/index.ts:42]:
```suggestion
    return Promise.all(Array.from(fns).map(fn => fn(param!)))
```

Comment (Alfred-Skyblue) [inline packages/shared/createEventHook/index.ts:42]: If this is the case, we can ensure that the length of the `arguments` is correct.
```ts
  const trigger: EventHookTrigger<T> = (...args) => {
    return Promise.all(Array.from(fns).map(fn => fn(...(args as [T]))))
  }
```

**Review by Alfred-Skyblue — APPROVED** [review]

**Comment by romansp** [comment]
There's also something wrong about type inference of `on` listeners when `createEventHook` is declared with union type.
I had to add `Falsy` type hint to `onResult` as otherwise it infers to `any` and  type of `onResult` explodes into `onResult: (fn: (() => void) | ((param: null) => void) | ((param: false) => void) | ((param: "") => void) | ((param: 0) => void)`;

May be worth opening another issue addressing that as it definitely wasn't the case before the changes introduced in #3507.

**Comment by Alfred-Skyblue** [comment]
We just need to pass all the arguments in the trigger to fn, we don't need to care what type it passes. I changed it to the following:

```ts
  const trigger: EventHookTrigger<T> = (...args) => {
    return Promise.all(Array.from(fns).map(fn => fn(...(args as [T]))))
  }
```
