### PR TITLE
fix(useMouse): position won't be changed on page scroll when `type` is `page`, closes #2922

### LINKED ISSUE #2922: useMouseInElement is not updating correctly on scroll for static element
### Describe the bug

While useMouse is totally correct to not update x or y value on scroll, this is not what should happen for the value of elementX, elementY and isOutside on useMouseInElement when the element is not sticky.

If I scroll on a page the position of the mouse is not changing which is correct, but scrolling move elements in the page thus changing the position of the mouse in this element.
Since useMouseInElement is not updating elementX, elementY and isOutside, on scroll they end up been false.

To reproduce the problem you can use the [doc](https://vueuse.org/core/useMouseInElement/) : 

place your cursor in the element then scoll, the elementX, elementY are not updating and if you scroll until the cursor is out of the element isOutside is still at false.

### Reproduction

https://vueuse.org/core/useMouseInElement/

### System Info

```Shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 119.64 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Firefox: 111.0
    Safari: 16.3
  npmPackages:
    @vueuse/core: ^9.13.0 => 9.13.0 
    vue: ^3.2.47 => 3.2.47
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by CatsJuice**
### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

When `type` is set to `page` (which is default), it's expected to update `x`, `y` when page is scrolled(related to issue #2922 ). I've added a `scrollTarget` option to enable scroll detection when `type` is `page`.

The mouse position of page should be updated when page scroll by recalculate the position in `scrollTarget`'s `scroll` event callback.

### Additional context

I wonder if the new option `scrollTarget` that I added is right. Maybe just add a `scroll?: boolean` will be better? Because the `page` type should related to window `scroll` event, and it's unnecessary to customize `scrollTarget`.

---

### <samp>🤖 Generated by Copilot at b410832</samp>

Add `scrollTarget` option to `useMouse` hook to track mouse or touch position relative to the page. Update `useMouse/index.ts` to handle scroll events and adjust position accordingly.

### <samp>🤖 Generated by Copilot at b410832</samp>

*  Add `scrollTarget` option to `UseMouseOptions` interface to customize the element for `scroll` events ([link](https://github.com/vueuse/vueuse/pull/3244/files?diff=unified&w=0#diff-acac08f31319ce15064e72bec03f921b9731164f2022b1a17ed4c09ba2864540R35-R42))
*  Declare `_prevMouseEvent` variable to store the last mouse or touch event on the `target` element ([link](https://github.com/vueuse/vueuse/pull/3244/files?diff=unified&w=0#diff-acac08f31319ce15064e72bec03f921b9731164f2022b1a17ed4c09ba2864540L72-R85))
*  Assign `event` parameter to `_prevMouseEvent` in `handler` function for `mousemove` or `touchmove` events ([link](https://github.com/vueuse/vueuse/pull/3244/files?diff=unified&w=0#diff-acac08f31319ce15064e72bec03f921b9731164f2022b1a17ed4c09ba2864540R96))
*  Define `scrollHandler` function to update `x` and `y` reactive values based on `_prevMouseEvent` and `window` scroll position ([link](https://github.com/vueuse/vueuse/pull/3244/files?diff=unified&w=0#diff-acac08f31319ce15064e72bec03f921b9731164f2022b1a17ed4c09ba2864540R114-R122))
*  Define `scrollHandlerWrapper` function to wrap `scrollHandler` with `eventFilter` option if provided ([link](https://github.com/vueuse/vueuse/pull/3244/files?diff=unified&w=0#diff-acac08f31319ce15064e72bec03f921b9731164f2022b1a17ed4c09ba2864540R136-R139))
*  Add `scroll` event listener on `scrollTarget` element using `useEventListener` hook with `scrollHandlerWrapper` as callback ([link](https://github.com/vueuse/vueuse/pull/3244/files?diff=unified&w=0#diff-acac08f31319ce15064e72bec03f921b9731164f2022b1a17ed4c09ba2864540R149-R150))

### CODE REVIEW

File: packages/core/useMouse/index.ts [hunk 1]
```diff
@@ -31,6 +31,14 @@ export interface UseMouseOptions extends ConfigurableWindow, ConfigurableEventFi
    */
   touch?: boolean
 
+  /**
+   * Customize scrollTarget to listen to `scroll` events for type `page`
+   * Set to `null` or `undefined` to disable
+   *
+   * @default null
```
Comment (antfu) [inline packages/core/useMouse/index.ts:38]: This does not align with the actual implementation. We could say this is enabled by default when type is `page`, and is only effective on type `page`?

File: packages/core/useMouse/index.ts [hunk 2]
```diff
@@ -99,6 +111,15 @@ export function useMouse(options: UseMouseOptions = {}) {
     }
   }
 
+  const scrollHandler = () => {
+    if (!_prevMouseEvent || !window || type !== 'page')
```
Comment (antfu) [inline packages/core/useMouse/index.ts:115]:
```suggestion
    if (!_prevMouseEvent || !window)
```

File: packages/core/useMouse/index.ts (hunk 1 above)
Comment (CatsJuice) [reply packages/core/useMouse/index.ts:38]: I'm not pretty sure that adding a scrollTarget is appropriate. Since `pageX` and `pageY` may not change if the `scrollTarget` is not `window`, it may be better to replace it with `scroll?: boolean`, which defaults to true when `type = "page"`.

When the scroll target is not a `window` but a custom element (e.g. `#app`) , user may need to customize `extractors` in order to get the mouse distance from the top coordinate.

In this case, there's a limit to what vueuse can handle, and it may only be able to cover the case where the `scrollTarget` is `window` and the `type` is `page`. 

I'm more confused about the API design here, so I wonder if I can change the options to `scroll?: boolean` and only handle the case where the `window` is the `scrollTarget`.

Comment (antfu) [reply packages/core/useMouse/index.ts:38]: Yes, I think `scroll?: boolean` makes sense

Comment (CatsJuice) [reply packages/core/useMouse/index.ts:38]: When the user really needs to use reactive mouse position in a custom element with the help of `useMouse`, it won't be possible. If we use `scrollTarget` with a user-defined `type` extractor, we can achieve it, but it's a bit tricky for the user to implement.

In this situation, use `useElementBounding` and `useMouse` together can also resolve the problem(like the solution in this [PR](https://github.com/CatsJuice/AFFiNE.pro/commit/a5d56d799e1494ba03431a99ab13f9245fc6c95d))

I'll change the option to `scroll?: boolean` first in current PR!

:)

**Comment by CatsJuice** [comment]
@antfu  By the way, I don't know why but when I pull the latest changes, it failed to run dev server.

I've found the reason but I'm not sure why and what happened as described in #3273

**Review by antfu — APPROVED** [review]
