### PR TITLE
fix(useScroll): Cannot read properties of null (reading document)

### LINKED ISSUE #3543: VueUse 1.6.0 - Cannot read properties of null (reading 'document')
### Describe the bug

With VueUse 1.6.0 I have got an error that is not present in version 1.5.0.
Error:
```
nuxt.js:97 [nuxt] error caught during app initialization TypeError: Cannot read properties of null (reading 'document')
```
In the reproduction I have produced error with using `useInfiniteScroll` function (found same for `useScroll`) and it happens because on top of ref element I have an element with conditional rendering. 
While testing, I have noticed that if I remove condition for rendering the element, error does not appear.
I have an example where I need the condition to be part of element tree that renders scrolling element and it worked in 1.5.0

### Reproduction

https://github.com/frasza/vueuse-nuxt-scroll

### System Info

```Shell
Nuxi info:
------------------------------
- Operating System: Windows_NT
- Node Version:     v20.9.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  pnpm@8.9.0
- Builder:          -
- User Config:      modules, ssr, devtools
- Runtime Modules:  @vueuse/nuxt@10.6.0, @nuxtjs/tailwindcss@6.9.4
- Build Modules:    -
------------------------------
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by Jokerzhzh**
### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

fixes #3543

### Additional context

In the PR #3384, triggered once `setArrivedState` when the component is first mounted.
When `element` is `null`, `setArrivedState` will still be triggered once.
This PR adds a judgment to avoid this problem.

---

### <samp>🤖 Generated by Copilot at 45bd3f0</samp>

Fix a bug in `useScroll` hook that caused state updates and errors when the element was null or undefined. Add a truthy check for `toValue(element)` before calling `setArrivedState` in `packages/core/useScroll/index.ts`.

### <samp>🤖 Generated by Copilot at 45bd3f0</samp>

* Fix a bug related to the `useScroll` hook that caused unnecessary state updates and potential errors when the element is null or undefined ([link](https://github.com/vueuse/vueuse/pull/3544/files?diff=unified&w=0#diff-6854b45663451a9e8c15d7b4e0bd17a681777359676d0a6c6d8dc32539bdcea6L254-R254))

### CODE REVIEW

File: packages/core/useScroll/index.ts [hunk 1]
```diff
@@ -251,7 +251,7 @@ export function useScroll(
   )
 
   tryOnMounted(() => {
-    setArrivedState(toValue(element))
+    toValue(element) && setArrivedState(toValue(element))
```
Comment (joaopslins) [inline packages/core/useScroll/index.ts:254]: I was literally opening a PR with this change but before doing that I checked and I saw this PR.

I think the below suggestion follows the guidelines better, given similar code logic in this file follows this style 🙇 

```suggestion
    const _element = toValue(element)
    if (!_element)
      return

    setArrivedState(_element)
```

**Review by antfu — APPROVED** [review]
