### PR TITLE
fix(useAsyncState): ensure `execute` return the actual data

### LINKED ISSUE #5111: BUG | `useAsyncState` | `execute()` should directly return the resolved data of the current promise after execution
### Describe the bug

In [the source code](https://github.com/vueuse/vueuse/blob/5628bdb05c18590bb500cc581a4ab1e1b05357a8/packages/core/useAsyncState/index.ts#L138), state.value is returned every time after execute() is executed. However, if execute() is called multiple consecutive times, the .then() of the non-last calls should obtain the resolved data of the current execution.

Here's a concrete bug example:

```ts
// Reactive object to store results
const dicts = reactive({})

// Mock async function: returns different data with different delays based on code
const getDict = async (code) => {
  if (code === 1) {
    await promiseTimeout(100) // Fastest: resolves after 100ms
    return { value: 'a', label: 'A' }
  } else if (code === 2) {
    await promiseTimeout(2000) // Slowest: resolves after 2000ms
    return { value: 'b', label: 'B' }
  } else {
    await promiseTimeout(1000) // Medium: resolves after 1000ms
    return { value: 'c', label: 'C' }
  }
}

const { isLoading, execute } = useAsyncState(getDict, undefined,{ immediate: false })

// 1st execution: should resolve to { value: 'a', ... }
execute(1).then((v) => {
  // ACTUAL: v is undefined (throws error when accessing v.value)
  // EXPECTED: v should be { value: 'a', label: 'A' }
  dicts[v.value] = v
})

// 2nd execution: should resolve to { value: 'b', ... }
execute(2).then((v) => {
  // ACTUAL: v is { value: 'c', label: 'C' } (overwritten by 3rd execution)
  // EXPECTED: v should be { value: 'b', label: 'B' }
  dicts[v.value] = v
})

// 3rd execution: should resolve to { value: 'c', ... }
execute(3).then((v) => {
  // ACTUAL: v is { value: 'c', label: 'C' } (only this one works)
  // EXPECTED: v should be { value: 'c', label: 'C' }
  dicts[v.value] = v
})
```

### Reproduction

https://playground.vueuse.org/?vueuse=14.0.0#eNqlVlGP4jYQ/iujvAASm8DuPSE4HbdHpVZ37el2K1Vq+mCcyeLdxI48TgAh/nvHCWHDCuhWJ/HgeMbffJ9nPMMumBdFWJUYTIIpSasKB4SuLCAT+mkWB47i4GOsVV4Y62AHhTW5InxUOZrSDaEknNNWywcnHMIeUrZD7xMjsiWSxmKvc9qikE5Vr47sx/ZYRxH8aG1m+YzSgTNAjs/zISoz5qGl0eQgUdIRzI5Y/d1+cID4ZuQLCE8H0lKz1egJ+7nSauJzaYoWNSMIJ2Ct3Kq7h5nYEiwFYQJGgzQJthGf0H3hoByzwe574wBmH2EXawCVNjswm81gPGg2AcRaKPfmvvrj0WgAzPQXQQ7JeXZksgoJROrQAttzVurPN7z50iqRlTiBnugNOStLzHg978Heu+0BM8JTCrfXKdyODhweMrM+x8E7XCSx7JD4fEriP3Q3Qb9hosr8nO7LMWUn5n0bM9b8azO0A0VfjUiUfhoCblCWdTHOTsuzf0gkV61OMFUakyGfzHPmxOYJpMLrOJbTmJEbsLqQaGXKLGmZ+/o8zU0Yhp7WIXx/PAjdCnW/X72WCoPO7x//nH+dQMWUX3lA362sWROgtcbCmg+CkBKJWBJUYR2HedUQi7++L+4fF188yIHUkq//aqHUr+bvA9A/fDMVX2Ar9FYn7xXq8/9G6O07hF5OJvRNhXZtlXOsebmFO9sh817J58ryquSTKNcle8ZvJN/9rGSdbcGt2MtohLWxL/RepecewyWl06hp6dzA+cNhXmRc5/wFME1UBTITRNzk0ww3oNhON5KbIb/H55KcSrft5/qGgZDzszos6qHgH6vHOSy5E7aPcAK7zpOE/X66tBAd/Wq+tU/TzPe1CgaLWrR2NY06rIMhjyN+8Kl6Cp/JaJ5Z9c3HgTR5oTK0fxQ+nTyyGLyBjAORcZ/7rd5ztsRhuy9XKF/O7D/Txu/FwXeuBrQVxsHR5oTlHtKYFw+/44bXR2NukjJj7yvGH76+6pJr3D5zA2DaHb+a7a/1vOSbe6TFhp8FtaI80br71f5xwOPz/or0V7p34Ye2a/ItNvP4JhfFm3tsDKcg7SynlbCYNLxXzhU0iSKZaEbg2akqG2p0kS7y6PTAp/GHcBSOOJ/kIsX9bsMnOoK7fxX+B7h3vwB9FLr/FzzB65o=

### System Info

```Shell
System:
    OS: Linux 6.14 Ubuntu 25.04 25.04 (Plucky Puffin)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 4.90 GB / 14.78 GB
    Container: Yes
    Shell: 5.2.37 - /bin/bash
  Binaries:
    Node: 22.17.1 - /run/user/1000/fnm_multishells/317555_1761111904305/bin/node
    npm: 10.9.2 - /run/user/1000/fnm_multishells/317555_1761111904305/bin/npm
  Browsers:
    Firefox: 144.0
    Firefox Developer Edition: 144.0
  npmPackages:
    @vueuse/core: ^14.0.0 => 14.0.0 
    vue: ^3.5.22 => 3.5.22
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vueuse.org/guide).
- [x] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by 9romise**
### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [ ] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [ ] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

Close #5111

### CODE REVIEW

**Comment by l246804** [comment]
👍

**Comment by antfu** [comment]
I wonder if we could consider this as a fix rather than a breaking change

**Review by antfu — APPROVED** [review]

File: packages/core/useAsyncState/index.ts [hunk 1]
```diff
@@ -7,8 +7,8 @@ export interface UseAsyncStateReturnBase<Data, Params extends any[], Shallow ext
   isReady: Ref<boolean>
   isLoading: Ref<boolean>
   error: Ref<unknown>
-  execute: (delay?: number, ...args: Params) => Promise<Data>
-  executeImmediate: (...args: Params) => Promise<Data>
+  execute: (delay?: number, ...args: Params) => Promise<Data | undefined>
```
Comment (antfu) [inline packages/core/useAsyncState/index.ts:10]: Maybe we should alter the return data type based on `throwError`?

**Comment by 9romise** [comment]
> I wonder if we could consider this as a fix rather than a breaking change

I agree. I've been on the fence about this too.

File: packages/core/useAsyncState/index.ts
Comment (antfu) [inline packages/core/useAsyncState/index.ts:70]: Unrelated to this PR tho, but I wonder if we should consider reverting this default. Not throwing error for a manual `execute` function by default feels a bit conterintutive to me

Comment (l246804) [reply packages/core/useAsyncState/index.ts:70]: Agree.

File: packages/core/useAsyncState/index.ts (hunk 1 above)
Comment (9romise) [reply packages/core/useAsyncState/index.ts:10]: Even if `throwError` is set to `false`, the return value of `execute` can still be `undefined`, because in the error branch we don’t have a valid `Data` to return. Therefore, I think the return type cannot reliably be narrowed based on `throwError`.

**Comment by l246804** [comment]
Any update on review/merge?
