### PR TITLE
fix(useScroll): account for rounding errors when calculating arrivedState

### LINKED ISSUE #2047: useScroll - right and bottom arrived not working in Desktop mode
### Describe the bug

Tested on your demo, and during my app development.

When the DIV uses standard desktop scrollbars, the two flags for `right` and `bottom` `arrived` do not work properly.
image

If I switch to "Responsive" in Chrome's developer tool, it now works as intended.
image

Note how the coordinates are slightly different between the two, probably due to the scrollbar thickness?

To reproduce:
- Open Chrome, your demo website for useScroll
- Go to the bottom-right, and notice how the `arrived` flags are still false
- Open the devtools, enable the "device" mode (mobile/responsive)
- Now the flag works properly, (and the scrollbars are thin)

### Reproduction

https://vueuse.org/core/usescroll/#demo

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 21.96 GB / 31.95 GB
  Binaries:
    Node: 16.14.2 - C:\Programming\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Programming\nodejs\yarn.CMD
    npm: 8.5.0 - C:\Programming\nodejs\npm.CMD
  Browsers:
    Chrome: 103.0.5060.134
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.77)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vueuse/core: 9.0.0 => 9.0.0
    vue: 3.2.37 => 3.2.37
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by curtgrimes**
### Description

Sometimes when zooming the page to sizes other than 100% and scrolling a
container all the way to the bottom right, the calculation for
`arrivedState.right` and `arrivedState.bottom` would incorrectly say
`false`. This is due to a [rounding error][] because `scrollTop` is a
non-rounded number, while `scrollHeight` and `clientHeight` are rounded.

Using the MDN documentation on `Element.scrollHeight` as guidance,
this commit factors in a 1px margin of error to more accurately
calculate `arrivedState.right` and `arrivedState.bottom`.

[rounding error]: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight#determine_if_an_element_has_been_totally_scrolled

fix #2047

---

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

File: packages/core/useScroll/index.ts [hunk 1]
```diff
@@ -114,7 +114,7 @@ export function useScroll(
     directions.right = scrollLeft > x.value
     arrivedState.left = scrollLeft <= 0 + (offset.left || 0)
     arrivedState.right
-          = scrollLeft + eventTarget.clientWidth >= eventTarget.scrollWidth - (offset.right || 0)
+      = scrollLeft + eventTarget.clientWidth >= eventTarget.scrollWidth - (offset.right || 0) - 1
```
Comment (antfu) [inline packages/core/useScroll/index.ts:117]: Can we make the magic `1` as an internal const and reference to the MDN docs?

Comment (curtgrimes) [reply packages/core/useScroll/index.ts]: Absolutely, good idea -- I pushed https://github.com/vueuse/vueuse/commit/638ceebcc01d531b1e72aa228ee40e66d05e247c. Thanks!

File: packages/core/useScroll/index.ts [hunk 2]
```diff
@@ -109,12 +109,18 @@ export function useScroll(
       e.target === document ? (e.target as Document).documentElement : e.target
     ) as HTMLElement
 
+    // We have to check if the scroll amount is close enough to some threshold in order to
+    // more accurately calculate arrivedState. This is because scrollTop/scrollLeft are non-rounded
+    // numbers, while scrollHeight/scrollWidth and clientHeight/clientWidth are rounded.
+    // https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight#determine_if_an_element_has_been_totally_scrolled
+    const arrivedStateThresholdPixels = 1
```
Comment (antfu) [inline packages/core/useScroll/index.ts:116]: A bit nitpicking but can we move it to top-level with UPPER_CASE? Thanks.

Comment (curtgrimes) [reply packages/core/useScroll/index.ts]: How does this look? Thanks! https://github.com/vueuse/vueuse/commit/a0d28a784659647a19c68eaedb6d0241d5cad4f9

**Review by antfu — APPROVED** [review]
