### PR TITLE
fix(useClipboard): prevents fail in Safari for async operation

### LINKED ISSUE #5368: BUG | `useClipboard` | fails in Safari for async operation
### Describe the bug

Unfortunately, for security reasons, Safari doesn't allow the Clipboard API to be used with async operations, so it fails without copying anything.
I've created a custom `useClipboardAsync` in [this PR in npmx](https://github.com/npmx-dev/npmx.dev/pull/2554) that handles the async call, so if interested, I could make similar changes directly in useClipboard here and remove my custom composable.

Would love to hear your thoughts on this! ❤️ 

### Reproduction

https://github.com/npmx-dev/npmx.dev/pull/2554

### System Info

```Shell
System:
  OS: macOS 26.3.1
  CPU: (10) arm64 Apple M4
  Memory: 1012.61 MB / 32.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 24.15.0 - /Users/matteo/.vite-plus/js_runtime/node/24.15.0/bin/node
  npm: 11.12.1 - /Users/matteo/.vite-plus/js_runtime/node/24.15.0/bin/npm
  pnpm: 10.33.0 - /Users/matteo/Library/pnpm/pnpm
  Deno: 2.0.6 - /opt/homebrew/bin/deno
Browsers:
  Brave Browser: 147.1.89.132
  Chrome: 147.0.7727.56
  Firefox: 149.0.2
  Safari: 26.3.1
npmPackages:
  @vueuse/core: 14.2.1 => 14.2.1
  @vueuse/integrations: 14.2.1 => 14.2.1
  @vueuse/nuxt: 14.2.1 => 14.2.1
  @vueuse/router: ^14.2.1 => 14.2.1
  @vueuse/shared: 14.2.1 => 14.2.1
  vue: 3.5.30 => 3.5.30
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vueuse.org/guide).
- [x] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by MatteoGabriele**
### Description

resolves #5368 

### Additional context
I've ensured compatibility with the current implementation to prevent breaking changes. The copy method still accepts an optional string, continuing to default from the source. Additionally, it now can also accept a function that returns a Promise resolving to a string. Since this operation can now be asynchronous, I've added a new `copyPending` boolean to enable showing a pending state when necessary.

This is my first time contributing to Vueuse, so let me know if I'm missing anything. I'm not too familiar with the codebase.

This could be a first draft. We can improve readability as well, if needed.
We could also decide to create a completely separate composable.

Thanks again for taking the time to read this ❤️

### CODE REVIEW

File: packages/core/useClipboard/index.ts [hunk 1]
```diff
@@ -130,6 +157,7 @@ export function useClipboard(options: UseClipboardOptions<MaybeRefOrGetter<strin
   }
 
   return {
+    copyPending,
```
Comment (OrbisK) [inline packages/core/useClipboard/index.ts]: this should be readonly:


```suggestion
    copyPending: shallowReadonly(copyPending),
```

File: packages/core/useClipboard/index.ts [hunk 2]
```diff
@@ -38,10 +38,15 @@ export interface UseClipboardOptions<Source> extends ConfigurableNavigator {
   legacy?: boolean
 }
 
+type ClipboardValue = string | (() => Promise<string | undefined>)
+
 export interface UseClipboardReturn<Optional> extends Supportable {
   text: Readonly<ShallowRef<string>>
   copied: Readonly<ShallowRef<boolean>>
-  copy: Optional extends true ? (text?: string) => Promise<void> : (text: string) => Promise<void>
+  copyPending: Readonly<ShallowRef<boolean>>
```
Comment (OrbisK) [inline packages/core/useClipboard/index.ts:46]: @43081j wdyt?

The non breaking `copy` function made sens to me. Because it fit into the current implementation. `copyPending` is now usefull but only used with async usage. Maybe we should better separate it?

File: packages/core/useClipboard/index.ts [hunk 3]
```diff
@@ -89,26 +95,47 @@ export function useClipboard(options: UseClipboardOptions<MaybeRefOrGetter<strin
...
+    else {
+      return new ClipboardItem({
+        'text/plain': value().then((resolvedText = '') => {
+          text.value = resolvedText
+          return new Blob([resolvedText], { type: 'text/plain' })
+        }),
+      })
+    }
+  }
+
```
Comment (MatteoGabriele) [inline packages/core/useClipboard/index.ts:151]: To simplify this, we can wrap the string in a Promise, which reduces the amount of code. If it's a string, it becomes a Promise<string>. If it's already a Promise<string>, we just use it.

Comment (OrbisK) [reply packages/core/useClipboard/index.ts:151]: not sure if we should do this. The check is cheaper than a promise

File: packages/core/useClipboard/index.ts (hunk 2 above)
Comment (MatteoGabriele) [reply packages/core/useClipboard/index.ts:46]: I wouldn't mind splitting it into a separate composable after having dug a bit more into the code, but that's just my 2 cents.
Usually, copy-pasting is a sync operation, and async is less frequent; that said, I still think it's needed.

Comment (43081j) [reply packages/core/useClipboard/index.ts:46]: i'd like to avoid two composables doing near enough the same thing.

the clipboard API is async under the hood so `copyPending` probably makes sense before this PR too even though it should never really be noticeable (i.e. most copies are fast).

i doubt many people will need an async copy but it is useful for those who do

File: packages/core/useClipboard/index.browser.test.ts [hunk 4]
```diff
@@ -19,6 +19,16 @@ describe('useClipboard', () => {
       expect(copied.value).toBe(true)
     })
 
+    it('should copy text from async function', async () => {
+      const { text, copy, copied } = useClipboard()
+      expect(text.value).toBe('')
+      expect(copied.value).toBe(false)
+
+      await copy(async () => 'async text')
```
Comment (43081j) [inline packages/core/useClipboard/index.browser.test.ts]: instead of an immediately resolved promise, can you pass one you manually `resolve()`? then assert that `copyPending` changes as expected

File: packages/core/useClipboard/index.ts [hunk 5]
```diff
@@ -89,26 +95,47 @@ export function useClipboard(options: UseClipboardOptions<MaybeRefOrGetter<strin
...
         try {
-          await navigator!.clipboard.writeText(value)
+          copyPending.value = true
+          const clipboardItem = createClipboardItem(resolvedValue)
+          await navigator!.clipboard.write([clipboardItem])
+          copyPending.value = false
         }
         catch {
           useLegacy = true
+          copyPending.value = false
```
Comment (OrbisK) [inline packages/core/useClipboard/index.ts]: lets move this to finally.

**Review by OrbisK — COMMENTED** [review]
This looks overall good to me.

One thing we have to discuss might be how we want to handle multiple pending async copies.

should we abort? I think `.write` does not support `AbortController` afaik.

**Comment by MatteoGabriele** [comment]
@OrbisK Yeah, there's no support for abort, but we could use the pending state to avoid triggering copy again until the previous operation is done.

**Comment by OrbisK** [comment]
> @OrbisK Yeah, there's no support for abort, but we could use the pending state to avoid triggering copy again until the previous operation is done.

I think we should not defer/dedupe it. I think copy should just do what it does. But I think we need to make sure that pending is true as long as all copies are not finished.

```ts
copy(simpleAsynCopy) // sets pending to true - takes 10 seconds
copy("sync value") // sets pending to true and immediate to false, but async is still pending

copyPending.value // should be true, but might be false
```

**Comment by 43081j** [comment]
just like your regular clipboard, new copy actions should discard the old ones i think.

```ts
const asyncValue = somehowGetAsyncValue("foo");
const syncValue = "bar";
const asyncValue2 = somehowGetAsyncValue("baz");

copy(asyncValue); // pending
copy(syncValue); // set clipboard to "bar", abandon the promise from before
copy(asyncValue2); // pending
// eventually, set clipboard to "baz" because the last promise resolved
```

**Comment by MatteoGabriele** [comment]
There may be a UX issue: 
- Copying async text "foo"
- Copying sync text "bar"
If the user clicks "foo" first, then "bar", it might copy "foo" instead of "bar" due to the delay.

**Comment by MatteoGabriele** [comment]
Love that we used a classic foobar action without knowing, ahahahahha
I see what you mean, though. The useClipboard instance should always get the last clicked "copy" value, regardless of which method. I'll see what I can do.

**Comment by 43081j** [comment]
i checked, the clipboard API writes the **last resolved** value.

so lets just do the same here and not implement our own behaviours.

this:

```ts
const asyncValue = somehowGetAsyncValue("foo");
const syncValue = "bar";
const asyncValue2 = somehowGetAsyncValue("baz");

copy(asyncValue); // pending
copy(syncValue); // set clipboard to "bar"
// asyncValue resolved, set clipboard to "foo"
copy(asyncValue2); // pending
// eventually, set clipboard to "baz" because the last promise resolved
```

**Comment by OrbisK** [comment]
> i checked, the clipboard API writes the **last resolved** value.
> 
> so lets just do the same here and not implement our own behaviours.
> 
> this:
> 
> ```ts
> const asyncValue = somehowGetAsyncValue("foo");
> const syncValue = "bar";
> const asyncValue2 = somehowGetAsyncValue("baz");
> 
> copy(asyncValue); // pending
> copy(syncValue); // set clipboard to "bar"
> // asyncValue resolved, set clipboard to "foo"
> copy(asyncValue2); // pending
> // eventually, set clipboard to "baz" because the last promise resolved
> ```

Nice! We still have to implement the "dedupe" for the legacy api. It currently await the resolve, so it will use the latest resolved value. We should handle this and we are good to go.

**Comment by MatteoGabriele** [comment]
@OrbisK I think this last change should do the trick

**Review by 43081j — DISMISSED** [review]

**Review by 43081j — APPROVED** [review]

**Review by OrbisK — APPROVED** [review]
Nice! Looks great! ❤️

**Review by 9romise — APPROVED** [review]
