### PR TITLE
fix(useFocus): `focused` should be `false` when `element` is undefined

### LINKED ISSUE #1560: useFocus demo abnormal when refresh
### Describe the bug

when u click the left sidebar menu , the router path is : https://vueuse.org/core/useFocus/  
**useFocus** the F is uppercase
and the focus state  of all three button is correct

BUT

when u refresh the page, the url path is :   https://vueuse.org/core/usefocus/

**usefocus** the F is lowercase

then the three buttons are in abnormal focus state

### Reproduction

https://vueuse.org/functions.html

### System Info

```Shell
System:
    OS: Windows 10 10.0.17134
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 4.99 GB / 15.78 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (42.17134.2208.0)
    Internet Explorer: 11.0.17134.1
  npmPackages:
    @vueuse/core: ^8.4.1 => 8.4.1
    vue: ^3.2.31 => 3.2.31
```

### Used Package Manager

yarn

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by webfansplz**
### Description

Closes #1560 

Caused by : both of the element to be `undefined` when the `Vitepress` generate HTML page.

image

### Additional context

---

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

File: packages/core/useFocus/index.ts [hunk 1]
```diff
@@ -36,6 +36,8 @@ export function useFocus(target: MaybeElementRef, options: UseFocusOptions = {})
   const targetElement = computed(() => unrefElement(target))
   const focused = computed({
     get() {
+      if (activeElement.value === undefined && targetElement.value === undefined)
+        return false
       return activeElement.value === targetElement.value
```
Comment (okxiaoliang4) [inline packages/core/useFocus/index.ts:41]:
```suggestion
      return isDef(activeElement.value) && isDef(targetElement.value) && activeElement.value === targetElement.value
```

**Review by okxiaoliang4 — APPROVED** [review]
