### PR TITLE
fix(useElementBounding): update on scroll

### LINKED ISSUE #2319: useElementBounding scroll inside element not working
### Describe the bug

When using some features like the `useElementBounding` feature, the scroll handler only triggers when the window gets scrolled. The values don't update if the scrolling happens inside an element (i.e. `overflow: scroll`).

Seems like this has worked some time in the past. While creating the reproduction I noticed that it suddenly worked (the version in the StackBlitz template is `^7.6.2`. After switching to `^9.3.0` it no longer worked)

### Reproduction

https://stackblitz.com/edit/vitejs-vite-fcit5l?file=src/Current.vue

### System Info

```Shell
❯ npx envinfo --system --npmPackages '{vue,@vueuse/*}' --binaries --browsers
success Install finished in 1.432s


  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @vueuse/core: ^9.3.0 => 9.3.0 
    vue: ^3.2.25 => 3.2.31
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by Ducz01**
### Description

Closes #2319, The Scrolling of useElementBounding didn't work when a div gets scrolled, only when the window was scrolled. Now it works.

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

File: packages/core/useElementBounding/index.ts [hunk 1]
```diff
@@ -93,7 +93,7 @@ export function useElementBounding(
   watch(() => unrefElement(target), ele => !ele && update())
 
   if (windowScroll)
-    useEventListener('scroll', update, { passive: true })
+    useEventListener('scroll', update, true, { passive: true })
```
Comment (sibbng) [inline packages/core/useElementBounding/index.ts:96]:
```suggestion
    useEventListener('scroll', update, { capture: true, passive: true })
```

**Review by sibbng — CHANGES_REQUESTED** [review]

**Review by dpschen — APPROVED** [review]

**Review by sibbng — APPROVED** [review]
