### PR TITLE
fix(useMediaQuery): only add/remove event listeners on query change

### LINKED ISSUE #3235: useMediaQuery event listeners are recreated every change event
### Describe the bug

#2178 changed the way how event listeners for `useMediaQuery` are created and disposed. Previously the update function was only responsible for changing the state, but currently it also both removes and re-creates the event listeners each time that function is called.

https://github.com/vueuse/vueuse/blob/658444bf9f8b96118dbd06eba411bb6639e24e88/packages/core/useMediaQuery/index.ts#L24-L53

If I understand correctly, this was done such that a media query that is passed as a ref would always have the most up to date event listeners in case the value for the ref changes, but besides that specific case, it seems unnecessary to recreate these listeners every time.

### Reproduction

https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wAjAAGSbEyak9bYLY7fYgI4nAhEHGIPHDGbWZ7sLhnDFfFA-GRyBS8ADCrAiiCgf3MrBMKBu2Fk+UKKkleDArGQMPkGWhshQCKRIBRgxGYwEQmms2GbI5XMQJPJlOpG0Q2z2hwAuswjHQDMa0KAAIJgMCTBboUCpLUGCCpIgAHio2QAfAAdcwqYDAJxFSpIAESRA2FQHA7Z5PDNPELMKZjiSQyIh0LV1aS5-w3ACyILoEAAiuQOGEDjUOLMVAByB03Tl1RAz7PZ-tp4ejkIlZDSSZgKcJUJgRCTAD6ECoVAAoh4VTvUthEPUALwqdeDkfP7d0Xf7w+sMep6Xjed7SA+NjPmuA6bt+D7-oBgEhCekwgbeNjgb+j7Piob5GPwsqijoECMKUjBQI4+YzNgbBBpMXjwNoM5oWBEFPhwM72AA3PEui-ueLEYWxz7aCRZEURWq7YB+sFjvBB6IUB57WHgrAeOh95YZBr7vjBX5yVhCFHshp4qWpiAaZhu7adBG76T+f4KcZKFmeprFaexuE1ARcrEaR5GUSo1G0aeDFMa5FnudZ7GcTx0h8cgym0OZlnCRwon+RJVbYNmwVdr+hYcMWpblm+eIyfZTHaPQ2AUJEdBUPFaAqI0ACspJgJs9icdmjKVkAA

### System Info

```Shell
N/A
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by Ingramz**
### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

This pull request changes `useMediaQuery` to only register event listeners when it is first created or when the reactive value for the passed in `query` changes in order to avoid re-creating the event listeners on every `change` event. This will avoid any excess overhead in the event handler itself.

Fixes #3235 

### Additional context

In the process, `toRef(query).value` was changed `toValue(query)`. I am not sure nor haven't tried yet whether this preserves the reactivity inside `watchEffect`. If this works as intended, it should be a slight improvement in bundled code size. Update: Reactivity seems to be working fine.

---

### <samp>🤖 Generated by Copilot at 4cf721b</samp>

Enhance `useMediaQuery` to support getter functions and fix a bug. Refactor the code for better performance and readability.

### <samp>🤖 Generated by Copilot at 4cf721b</samp>

*  Replace `toRef` with `toValue` to support `MaybeRefOrGetter` type for `query` argument of `useMediaQuery` ([link](https://github.com/vueuse/vueuse/pull/3236/files?diff=unified&w=0#diff-d9533c610c4da5a1c5a0e03fc40091a2a8834c552c81ffc974287a7d4f7d53f1L5-R5), [link](https://github.com/vueuse/vueuse/pull/3236/files?diff=unified&w=0#diff-d9533c610c4da5a1c5a0e03fc40091a2a8834c552c81ffc974287a7d4f7d53f1L42-R45))
*  Move and modify `update` and `cleanup` functions to improve performance, readability, and bug fix ([link](https://github.com/vueuse/vueuse/pull/3236/files?diff=unified&w=0#diff-d9533c610c4da5a1c5a0e03fc40091a2a8834c552c81ffc974287a7d4f7d53f1L24-R39), [link](https://github.com/vueuse/vueuse/pull/3236/files?diff=unified&w=0#diff-d9533c610c4da5a1c5a0e03fc40091a2a8834c552c81ffc974287a7d4f7d53f1L53-R61))
*  Move `watchEffect` call inside `stopWatch` variable and pass it to `tryOnScopeDispose` to avoid unnecessary effects and ensure proper cleanup ([link](https://github.com/vueuse/vueuse/pull/3236/files?diff=unified&w=0#diff-d9533c610c4da5a1c5a0e03fc40091a2a8834c552c81ffc974287a7d4f7d53f1L53-R61))

### CODE REVIEW

File: packages/core/useMediaQuery/index.ts [hunk 1]
```diff
@@ -21,39 +21,44 @@ export function useMediaQuery(query: MaybeRefOrGetter<string>, options: Configur
...
       return
 
     cleanup()
 
-    mediaQuery = window!.matchMedia(toRef(query).value)
+    mediaQuery = window!.matchMedia(toValue(query))
     matches.value = !!mediaQuery?.matches
 
     if (!mediaQuery)
       return
```
Comment (Ingramz) [inline packages/core/useMediaQuery/index.ts:48]: It should be possible to assert that if `isSupported.value = true`, then `window.matchMedia` always returns a `MediaQueryList` unless there exists a noncompliant implementation that this aims to handle.

**Review by antfu — DISMISSED** [review]

**Comment by Ingramz** [comment]
I think there's a test failure right now caused by a `window.matchMedia` mock that returns undefined instead of a MediaQueryList. Can take a look at it a bit later if necessary.

**Review by antfu — APPROVED** [review]
