### PR TITLE
fix(useDraggable): use `clientX` instead of `pageX`, close #2053

### LINKED ISSUE #2053: useDraggable with scrolling
### Describe the bug

When dragging an element on the https://vueuse.org/core/usedraggable page, then scrolling and moving the mouse a bit, the element will jump a fair bit.

Steps to reproduce
1. go to https://vueuse.org/core/usedraggable 
2. start dragging the element that says "drag me!"
3. scroll down with the mouse wheel
4. move the mouse a bit
5. stop dragging the element

### Reproduction

https://vueuse.org/core/usedraggable

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz    
    Memory: 19.06 GB / 31.86 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.16.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.47) 
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vueuse/core: link:packages/core => 9.1.0 
    @vueuse/integrations: link:packages/integrations => 9.1.0 
    @vueuse/math: link:packages/math => 9.1.0 
    @vueuse/shared: link:packages/shared => 9.1.0 
    vue: ^3.2.37 => 3.2.37
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by stefnotch**
### Description
Fix #2053 

### Additional context

---

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

File: packages/core/useDraggable/index.ts [hunk 1]
```diff
@@ -96,8 +96,8 @@ export function useDraggable(target: MaybeComputedRef<HTMLElement | SVGElement |
       return
     const rect = resolveUnref(target)!.getBoundingClientRect()
     const pos = {
-      x: e.pageX - rect.left,
-      y: e.pageY - rect.top,
+      x: e.clientX - rect.left,
+      y: e.clientY - rect.top,
```
Comment (stefnotch) [inline packages/core/useDraggable/index.ts:100]: One interesting tidbit is that this pretty much assumes "position: fixed". That's also the only thing that can be implemented in a sane manner, as far as I can tell.

**Comment by stefnotch** [comment]
Still fixes a major bug for me

**Comment by stefnotch** [comment]
The demo on the documentation site is still bugged, so I assume that this fix is still relevant.
