### PR TITLE
fix(useAxios): assign AxiosError to error.value when no url provided (close #2478)

### LINKED ISSUE #2478: [useAxios] Test case `missing url` doesn't pass.
### In a word
<details>
<summary>
Here's the original output of Vitest.
</summary>

```shell
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  packages/integrations/useAxios/index.test.ts > useAxios > missing url
AssertionError: expected undefined not to be undefined
 ❯ packages/integrations/useAxios/index.test.ts:281:25
    279|     const { execute } = useAxios(und…
    280|     const { error } = await execute()
    281|     expect(error.value).toBeDefined()
       |                         ^
    282|   })
    283| })

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed | 125 passed (126)
      Tests  1 failed | 813 passed (814)
   Start at  19:11:09
   Duration  99.82s


 FAIL  Tests failed. Watching for file changes...
```
</details>

### About the reason

After logging, I found that `error.value` here is `undefined`.

**The reason is that in `execute` function, `_url` is assigned a default `''` (empty string) when it's undefined.** Therefore, `axios` doesn't walk into the `catch` branch.

### My solution

I'll open a PR later and mention it below.

### Reproduction

Clone https://github.com/syy11cn/vueuse and run `pnpm run test`.

### System Info

```Shell
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M2
    Memory: 59.03 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Safari: 16.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by syy11cn**
### Description

Fixes #2478 .

Test case `missing url` for `useAxios` expects `error.value` to be defined when url is missing. However, currently it is `undefined`.

I assigned an `AxioxError` to `error.value` when url is missing at calling `useAxios`.

```diff
const execute: OverallUseAxiosReturn<T, R, D>['execute'] = (executeUrl: string | AxiosRequestConfig<D> | undefined = url, config: AxiosRequestConfig<D> = {}) => {
    error.value = undefined
-    const _url = typeof executeUrl === 'string'
+    let _url = typeof executeUrl === 'string'
      ? executeUrl
-      : url ?? ''
+      : url ?? config.url

+    if (_url === undefined) {
+     error.value = new AxiosError(AxiosError.ERR_INVALID_URL)
+      _url = ''
+   }

    loading(true)
    instance(_url, { ...defaultConfig, ...typeof executeUrl === 'object' ? executeUrl : config, cancelToken: cancelToken.token })
      .then((r: any) => {
        response.value = r
        data.value = r.data
      })
      .catch((e: any) => {
        error.value = e
      })
      .finally(() => loading(false))
    return { then }
  }
```

**Test case `missing url` is now passing with this PR.**

### Additional context

Null.

---

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

File: packages/integrations/useAxios/index.ts [hunk 1]
```diff
@@ -176,9 +176,15 @@ export function useAxios<T = any, R = AxiosResponse<T>, D = any>(...args: any[])
...
     error.value = undefined
-    const _url = typeof executeUrl === 'string'
+    let _url = typeof executeUrl === 'string'
       ? executeUrl
-      : url ?? ''
+      : url ?? config.url
+
+    if (_url === undefined) {
+      error.value = new AxiosError(AxiosError.ERR_INVALID_URL)
+      _url = ''
```
Comment (wheatjs) [inline packages/integrations/useAxios/index.ts:185]: Are we sure we want to reassign the url? If we do then the axios request will still fire even though we gave the user an error, right?

Comment (syy11cn) [reply packages/integrations/useAxios/index.ts]: Yeah, you are right. Updated the code. Thanks for reviewing! 💚

**Review by wheatjs — APPROVED** [review]
