### PR TITLE
fix(onClickOutside): put ignore logic on `pointerdown` event

### LINKED ISSUE #2196: onClickOutside: listen only to mousedown event for ignore elements
### Describe the bug

Hi! 👋

If I click inside an ignore element  then release my mouse outside of it and the target, the handler function is called.

In a previous version of vueUse, it was possible to specifiy which events should trigger the handler ( see https://github.com/vueuse/vueuse/pull/508/commits/e080ec61f8b99527f45458b4d7d9de3ee378f3b8)

I'm not sure if this was also applied to ignore elements, but the option was then removed in this commit https://github.com/vueuse/vueuse/commit/2ff6ca9b0b1cf3f3ea885c9130d3b417f680b5cd

Why the option has been removed? Could it be possible to bring it back? How can I do to not trigger the handler function?

### Reproduction

https://stackblitz.com/edit/vitejs-vite-jkw1v5/?file=src%2FApp.vue

### System Info

```Shell
vueuse stackblitz
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by GODLiangCY**
### Description

fix #2196 

### Additional context

put ignore logic on `pointerdown` event, making sure the proper behavior.

---

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

File: packages/core/onClickOutside/index.ts [hunk 1]
```diff
@@ -54,22 +54,28 @@ export function onClickOutside<T extends OnClickOutsideOptions>(
...
+
+    const composedPath = event.composedPath()
+    if (ignore.some((target) => {
+      const el = unrefElement(target)
+      return el && (event.target === el || composedPath.includes(el))
+    }))
+      return true
+
+    return false
+  }
```
Comment (sibbng) [inline packages/core/onClickOutside/index.ts:72]:
```suggestion
  const shouldIgnore = (event: PointerEvent) => {
    return ignore && ignore.some((target) => {
      const el = unrefElement(target)
      return el && (event.target === el || event.composedPath().includes(el))
    })
  }
```

File: packages/core/onClickOutside/index.ts [hunk 2]
```diff
@@ -54,22 +54,28 @@ export function onClickOutside<T extends OnClickOutsideOptions>(
     if (!el || el === event.target || composedPath.includes(el) || !shouldListen.value)
```
Comment (sibbng) [inline packages/core/onClickOutside/index.ts:54]:
```suggestion
    if (!el || el === event.target || event.composedPath.includes(el) || !shouldListen.value)
```

**Review by sibbng — CHANGES_REQUESTED** [review]

**Review by sibbng — APPROVED** [review]
