### PR TITLE
fix(useSpeechRecognition): catch the error while calling method start

### LINKED ISSUE #5135: BUG | `SpeechRecognition` | Failed to execute 'start' on 'SpeechRecognition': recognition has already started  on mobile devices
### Description
There's an issue with error handling in the `useSpeechRecognition` composable on **mobile devices** when microphone permissions are denied.

### Steps to Reproduce
- Initially deny microphone access in the browser
- Click the voice search button for the first time - error is properly caught in the error property
- Click the voice search button again - the error is not captured in the error property but appears in the browser console instead

### Actual Behavior
- First click: Error is properly captured in error property (e.g., "NotAllowedError")
- Second click: Error "InvalidStateError: Failed to execute 'start' on 'SpeechRecognition': recognition has already started." appears in browser console but is not captured in the error property

### Reproduction

https://codesandbox.io/p/sandbox/12321-pyq2f7

### System Info

```Shell
System:
    OS: Mobile (Android 14/iOS 17.2.1) 
Browsers:
    Chrome: 141.0.7390.122
    Safari: 17.2.1
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vueuse.org/guide).
- [x] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by ben-lau**
### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vueuse/vueuse/blob/main/packages/guidelines.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

<details>
<summary><strong>⚠️ Slowing down new functions</strong></summary>
<br>

> **Warning**: **Slowing down new functions**
>
> As the VueUse audience continues to grow, we have been inundated with an overwhelming number of feature requests and pull requests. As a result, maintaining the project has become increasingly challenging and has stretched our capacity to its limits. As such, in the near future, we may need to slow down our acceptance of new features and prioritize the stability and quality of existing functions. **Please note that new features for VueUse may not be accepted at this time.** If you have any new ideas, we suggest that you first incorporate them into your own codebase, iterate on them to suit your needs, and assess their generalizability. If you strongly believe that your ideas are beneficial to the community, you may submit a pull request along with your use cases, and we would be happy to review and discuss them. Thank you for your understanding.

</details>

---

### Description

resolved #5135 .
This appears to be an implementation issue with SpeechRecognition on mobile devices; similar problems occurred in earlier PC browsers. [here](https://techcommunity.microsoft.com/discussions/edgeinsiderdiscussions/web-speech-api-support-/1104645)
I used try-catch to catch the error and categorized it into the error object,  so that errors can be managed uniformly.

### CODE REVIEW

File: packages/core/useSpeechRecognition/index.ts [hunk 1]
```diff
@@ -120,10 +120,17 @@ export function useSpeechRecognition(options: UseSpeechRecognitionOptions = {})
...
+      try {
+        if (newValue) {
+          recognition!.start()
+        }
+        else {
+          recognition!.stop()
+        }
+      }
+      catch (err: unknown) {
+        error.value = err as unknown as SpeechRecognitionErrorEvent
```
Comment (OrbisK) [inline packages/core/useSpeechRecognition/index.ts]: is this error always `SpeechRecognitionErrorEvent`?

Comment (ben-lau) [reply packages/core/useSpeechRecognition/index.ts]: no, in this situation it will be `DOMException`, I set it to `Error` so that it could include other errors.

**Review by antfu — APPROVED** [review]
